### ISSUE TITLE
🐛 VS Code extension prints warning although biome is not being used

### ISSUE THREAD

**Issue by nhedger** [biomejs/biome#115]
### Environment information

```block
CLI:
  Version:                      1.0.0
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v18.13.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "null"

Biome Configuration:
  Status:                       unset

Workspace:
  Open Documents:               0

Discovering running Biome servers...

Incompatible Biome Server: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ℹ Rage discovered this running server using an incompatible version of Biome.

Server:
  Version:                      <=10.0.0
```

### What happened?

The biome VS Code extension shows a warning message in a project that does not use biome at all.

The extension is configured with `Biome: require configuration` set to `true`.

```
The extension couldn't resolve @biomejs/cli-darwin-x64/package.json or @biomejs/cli-darwin-x64/biome.
If you installed "@biomejs/biome", it's a resolving issue due to your package manager. 
Check the troubleshooting section of the extension for more information on how to fix the issue.
```

### Expected result

The VS Code extension does not activate Biome in projects that do not use Biome.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by nhedger** [comment]
I may be able to contribute a fix for this issue, but I'd like to make sure we all agree on the expected behaviour.

IMHO, the extension should not attempt to locate the server path if the following is true:

- The `biome.requireConfiguration` is set to `true` (default), **and** the project does not have a `rome.json` (until completely removed) or `biome.json` file.

**Comment by ematipico** [comment]
So, I put that warning because when I tested the extension before the launch, the extension couldn't resolve the binaries. That was a problem with `pnpm`. 

That was a hasty, quick fix I put in place in case someone faced my same issue. I now realise this is a bug and **not** the intended behaviour.

One thing we could do is to try to resolve `@biomejs/biome` **first**. If the package is not found, we return `undefined` and carry on:
https://github.com/biomejs/biome/blob/06f28896981764dd430b313d4a303b02cb87aada/editors/vscode/src/main.ts#L223


If `@biomejs/biome` is found, we should continue with the logic and maybe keep the warning. What do you think?

**Comment by nhedger** [comment]
There are two issues here IMHO:

1. The Biome extension attempts to located the server in project that do not use Biome
2. The Biome extension fails to locate the server

### Should we attempt to locate the server?

The [activation events](https://github.com/biomejs/biome/blob/86b5fdc9d63bdd5f13e0737af5acff15d5b2f9b2/editors/vscode/package.json#L8-L16) of the extension are broad. This is fine, but it also means that it is very likely that it will activate in projects that do not use Biome at all. The extension should handle this transparently for the users.

We should probably rely on the `biome.requireConfiguration` and the presence of the `biome.json` config file.

```mermaid
flowchart LR

A(Extension activates) --> B{biome.requireConfiguration}
B -->|true| D{biome.json exists}
B -->|false| Z
D -->|true| Z
D -->|false| Y
Y(Do nothing)
Z(Attempt to locate server)
```

### Locating the server

When it comes to locating the server, it think it should attempt to find the server in the following order.


```mermaid
flowchart LR

A(Locating the server) --> B{biomejs/biome exists\n in local dependencies}
B -->|true| Z
B -->|false| C{biomejs/biome exists\n in global dependencies}
C -->|true| Z
C -->|false| D{Builtin biome supports arch}
D -->|true| Z
D -->|false| Y
Y(Server not found - show warning)
Z(Server found)
```

**Comment by ematipico** [comment]
The proposed solution makes sense to me, although we vehemently discourage the installation of the package globally, so we should refrain from attempting to discover it globally.

**Comment by nhedger** [comment]
Sounds good

**Comment by nhedger** [comment]
I have started working on this.

**Comment by nhedger** [comment]
Fixed by https://github.com/biomejs/biome/pull/210

**Comment by diminutivesloop** [comment]
Was there a regression here? I'm still getting prompts on projects that don't have any Biome configuration. Also the extension does not appear to have a `biome.requireConfiguration` setting anymore.
<img width="1286" alt="Screenshot 2024-01-17 at 2 12 00 PM" src="https://github.com/biomejs/biome/assets/121306735/59c53273-94f7-4545-bd90-699235d1fdbb">

**Comment by imranbarbhuiya** [comment]
I'm also having the same prompt and it's really annoying

**Comment by rikisamurai** [comment]
Is there any solution?
