### ISSUE TITLE
💅 Biome encountered an unexpected error when setting noExplicitAny=off in an override in CLI

### ISSUE THREAD

**Issue by SalvatorePreviti** [biomejs/biome#1349]
### Environment information

```bash
CLI:
  Version:                      1.4.1
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v18.18.2"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/9.8.1"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 false

Workspace:
  Open Documents:               0
```

### Rule name

noExplicitAny, but seems to happens with other rules when includes is used

### Expected result

No errors when running the CLI.

I get this:

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates/biome_service/src/configuration/linter/mod.rs:167:18
Thread Name: biome::worker_6
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates/biome_service/src/configuration/linter/mod.rs:167:18
Thread Name: biome::worker_1
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

./test/dev/devChildTask/dev-child-task.test.ts internalError/panic  INTERNAL  ━━━━━━━━━━━━━━━━━━━━━━

  ✖ processing panicked: internal error: entered unreachable code: the rule is turned off, it should not step in here

  ⚠ This diagnostic was derived from an internal Biome error. Potential bug, please report it if necessary.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
This should be fixed in the next release.

**Comment by fb55** [comment]
Still getting this error in 1.5.1. Other disables work, `noExplicitAny` errors.

```
  ✖ processing panicked: internal error: entered unreachable code: the rule is turned off, it should not step in here
  
  ⚠ This diagnostic was derived from an internal Biome error. Potential bug, please report it if necessary.
  ```

**Comment by BC-M** [comment]
Got the same issue with`lint/performance/noDelete`:

```json
"overrides": [
    {
      "include": ["*.spec.ts", "*.spec.tsx"],
      "linter": {
        "rules": {
          "performance": {
            "noDelete": "off"
          }
        }
      }
    }
  ]
```

or even with an empty rules-object:

```json
"overrides": [
    {
      "include": ["*.spec.ts", "*.spec.tsx"],
      "linter": {
        "rules": {}
      }
    }
  ]
```

We are using biome 1.5.2.

**Comment by ematipico** [comment]
Use our Codesandbox template: https://codesandbox.io/p/sandbox/biome-starter-cbs-rky6zq

**Comment by BC-M** [comment]
> Use our Codesandbox template: https://codesandbox.io/p/sandbox/biome-starter-cbs-rky6zq

Thank you! Here it is: https://codesandbox.io/p/devbox/divine-waterfall-wqglgc Just run `npm run check` in terminal.

<details><summary>Output</summary>

```

➜  /workspace git:(master) npm run check

> biome-sandbox@1.0.0 check
> biome check ./src

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates/biome_service/src/configuration/linter/mod.rs:186:18
Thread Name: biome::worker_0
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

./src/utils.spec.ts internalError/panic  INTERNAL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ processing panicked: internal error: entered unreachable code: the rule is turned off, it should not step in here
  
  ⚠ This diagnostic was derived from an internal Biome error. Potential bug, please report it if necessary.
  

Checked 2 file(s) in 2ms

```

</details>

**Comment by nstepien** [comment]
I ran into a similar issue, but instead I'm enabling a rule in an override. The rule is otherwise turned off.

<details>
  <summary>config</summary>

```json
{
  "$schema": "./node_modules/@biomejs/biome/configuration_schema.json",
  "files": {
    "ignore": [
      "./.cache/**/*",
      "./coverage/**/*",
      "./node_modules/**/*",
      "./translations/**/*"
    ]
  },
  "formatter": {
    "ignore": ["*.ts", "*.tsx"],
    "indentStyle": "space"
  },
  "json": {
    "parser": {
      "allowComments": true
    }
  },
  "javascript": {
    "formatter": {
      "quoteStyle": "single",
      "trailingComma": "none"
    }
  },
  "linter": {
    "rules": {
      "recommended": false,
      "a11y": {
        "noAccessKey": "warn",
        "noAriaHiddenOnFocusable": "warn",
        "noAriaUnsupportedElements": "warn",
        "noAutofocus": "off",
        "noBlankTarget": "warn",
        "noDistractingElements": "warn",
        "noHeaderScope": "warn",
        "noInteractiveElementToNoninteractiveRole": "warn",
        "noNoninteractiveElementToInteractiveRole": "warn",
        "noNoninteractiveTabindex": "off",
        "noPositiveTabindex": "warn",
        "noRedundantAlt": "warn",
        "noRedundantRoles": "warn",
        "noSvgWithoutTitle": "off",
        "useAltText": "warn",
        "useAnchorContent": "warn",
        "useAriaActivedescendantWithTabindex": "warn",
        "useAriaPropsForRole": "warn",
        "useButtonType": "warn",
        "useHeadingContent": "warn",
        "useHtmlLang": "warn",
        "useIframeTitle": "off",
        "useKeyWithClickEvents": "off",
        "useKeyWithMouseEvents": "warn",
        "useMediaCaption": "off",
        "useValidAnchor": "off",
        "useValidAriaProps": "warn",
        "useValidAriaRole": "warn",
        "useValidAriaValues": "warn",
        "useValidLang": "warn"
      },
      "complexity": {
        "noBannedTypes": "warn",
        "noExcessiveCognitiveComplexity": "off",
        "noExtraBooleanCast": "warn",
        "noForEach": "off",
        "noMultipleSpacesInRegularExpressionLiterals": "warn",
        "noStaticOnlyClass": "warn",
        "noThisInStatic": "warn",
        "noUselessCatch": "warn",
        "noUselessConstructor": "warn",
        "noUselessEmptyExport": "warn",
        "noUselessFragments": "warn",
        "noUselessLabel": "warn",
        "noUselessRename": "warn",
        "noUselessSwitchCase": "warn",
        "noUselessThisAlias": "warn",
        "noUselessTypeConstraint": "warn",
        "noVoid": "warn",
        "noWith": "warn",
        "useArrowFunction": "warn",
        "useFlatMap": "warn",
        "useLiteralKeys": "warn",
        "useOptionalChain": "warn",
        "useRegexLiterals": "warn",
        "useSimpleNumberKeys": "warn",
        "useSimplifiedLogicExpression": "off"
      },
      "correctness": {
        "noChildrenProp": "off",
        "noConstAssign": "warn",
        "noConstantCondition": "warn",
        "noConstructorReturn": "warn",
        "noEmptyCharacterClassInRegex": "warn",
        "noEmptyPattern": "warn",
        "noGlobalObjectCalls": "warn",
        "noInnerDeclarations": "warn",
        "noInvalidConstructorSuper": "warn",
        "noInvalidNewBuiltin": "warn",
        "noNewSymbol": "warn",
        "noNonoctalDecimalEscape": "warn",
        "noPrecisionLoss": "warn",
        "noRenderReturnValue": "warn",
        "noSelfAssign": "warn",
        "noSetterReturn": "warn",
        "noStringCaseMismatch": "warn",
        "noSwitchDeclarations": "warn",
        "noUndeclaredVariables": "off",
        "noUnnecessaryContinue": "warn",
        "noUnreachable": "warn",
        "noUnreachableSuper": "warn",
        "noUnsafeFinally": "warn",
        "noUnsafeOptionalChaining": "warn",
        "noUnusedLabels": "warn",
        "noUnusedVariables": "off",
        "noVoidElementsWithChildren": "warn",
        "noVoidTypeReturn": "warn",
        "useExhaustiveDependencies": "warn",
        "useHookAtTopLevel": "warn",
        "useIsNan": "warn",
        "useValidForDirection": "warn",
        "useYield": "warn"
      },
      "performance": {
        "noAccumulatingSpread": "warn",
        "noDelete": "warn"
      },
      "security": {
        "noDangerouslySetInnerHtml": "warn",
        "noDangerouslySetInnerHtmlWithChildren": "warn"
      },
      "style": {
        "noArguments": "warn",
        "noCommaOperator": "warn",
        "noDefaultExport": "off",
        "noImplicitBoolean": "off",
        "noInferrableTypes": "warn",
        "noNamespace": "warn",
        "noNegationElse": "off",
        "noNonNullAssertion": "off",
        "noParameterAssign": "off",
        "noParameterProperties": "warn",
        "noRestrictedGlobals": "warn",
        "noShoutyConstants": "warn",
        "noUnusedTemplateLiteral": "warn",
        "noUselessElse": "warn",
        "noVar": "warn",
        "useAsConstAssertion": "warn",
        "useBlockStatements": "off",
        "useCollapsedElseIf": "warn",
        "useConst": "warn",
        "useDefaultParameterLast": "off",
        "useEnumInitializers": "warn",
        "useExponentiationOperator": "warn",
        "useFragmentSyntax": "warn",
        "useLiteralEnumMembers": "warn",
        "useNamingConvention": "off",
        "useNumericLiterals": "warn",
        "useSelfClosingElements": "warn",
        "useShorthandArrayType": "warn",
        "useShorthandAssign": "warn",
        "useSingleCaseStatement": "off",
        "useSingleVarDeclarator": "warn",
        "useTemplate": "warn",
        "useWhile": "warn"
      },
      "suspicious": {
        "noApproximativeNumericConstant": "warn",
        "noArrayIndexKey": "off",
        "noAssignInExpressions": "off",
        "noAsyncPromiseExecutor": "warn",
        "noCatchAssign": "warn",
        "noClassAssign": "warn",
        "noCommentText": "warn",
        "noCompareNegZero": "warn",
        "noConfusingLabels": "warn",
        "noConfusingVoidType": "warn",
        "noConsoleLog": "warn",
        "noConstEnum": "warn",
        "noControlCharactersInRegex": "warn",
        "noDebugger": "warn",
        "noDoubleEquals": "warn",
        "noDuplicateCase": "warn",
        "noDuplicateClassMembers": "warn",
        "noDuplicateJsxProps": "warn",
        "noDuplicateObjectKeys": "warn",
        "noDuplicateParameters": "warn",
        "noEmptyInterface": "warn",
        "noExplicitAny": "warn",
        "noExtraNonNullAssertion": "warn",
        "noFallthroughSwitchClause": "warn",
        "noFunctionAssign": "warn",
        "noGlobalIsFinite": "warn",
        "noGlobalIsNan": "warn",
        "noImplicitAnyLet": "off",
        "noImportAssign": "warn",
        "noLabelVar": "warn",
        "noMisleadingInstantiator": "warn",
        "noMisrefactoredShorthandAssign": "warn",
        "noPrototypeBuiltins": "warn",
        "noRedeclare": "warn",
        "noRedundantUseStrict": "warn",
        "noSelfCompare": "warn",
        "noShadowRestrictedNames": "warn",
        "noSparseArray": "warn",
        "noUnsafeDeclarationMerging": "warn",
        "noUnsafeNegation": "warn",
        "useDefaultSwitchClauseLast": "warn",
        "useGetterReturn": "warn",
        "useIsArray": "warn",
        "useNamespaceKeyword": "warn",
        "useValidTypeof": "warn"
      }
    }
  },
  "organizeImports": {
    "enabled": false
  },
  "overrides": [
    {
      "include": ["**/*.js"],
      "linter": {
        "rules": {
          "suspicious": {
            "noConsoleLog": "off"
          }
        }
      }
    },
    {
      "include": ["./src/MediaCampaign/**/*"],
      "linter": {
        "rules": {
          "complexity": {
            "noForEach": "warn"
          }
        }
      }
    }
  ]
}
```
</details>

<details>
  <summary>cli output</summary>

```
Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_4
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_34
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_15
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_34
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_8
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_44
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_2
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_41
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_34
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_31
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_35
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_28
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_2
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_30
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_50
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_15
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_34
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_45
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_6
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_52
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_13
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_30
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_20
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_15
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_40
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_39
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_2
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_32
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_14
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_28
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_8
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_18
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_34
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_0
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_27
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_37
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_26
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_29
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_25
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_32
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_18
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_6
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_22
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_42
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_2
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_11
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_46
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_30
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_16
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_18
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_60
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_25
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_58
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_34
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_32
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_59
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_20
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_40
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_9
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_4
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_10
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_13
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_33
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_18
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_35
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_26
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_62
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_14
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_11
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_3
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_61
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_44
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_20
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_17
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_46
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_2
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_54
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_22
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_39
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_40
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_10
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_47
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_0
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_12
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_36
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_49
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_59
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_31
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_42
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_5
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_34
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_26
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_13
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_48
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_21
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_24
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_53
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_38
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_23
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_1
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_35
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_18
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_43
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_45
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_41
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates\biome_service\src\configuration\linter\mod.rs:186:18
Thread Name: biome::worker_55
Message: internal error: entered unreachable code: the rule is turned off, it should not step in here

.\src\path\file.ts internalError/panic  INTERNAL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 

  × processing panicked: internal error: entered unreachable code: the rule is turned off, it should not step in here

  ! This diagnostic was derived from an internal Biome error. Potential bug, please report it if necessary.


.\src\path\file.ts internalError/panic  INTERNAL  ━━━━━━━━━━━━━

  × processing panicked: internal error: entered unreachable code: the rule is turned off, it should not step in here

  ! This diagnostic was derived from an internal Biome error. Potential bug, please report it if necessary.


.\src\path\file.ts internalError/panic  INTERNAL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 

  × processing panicked: internal error: entered unreachable code: the rule is turned off, it should not step in here

  ! This diagnostic was derived from an internal Biome error. Potential bug, please report it if necessary.


.\src\path\file.ts internalError/panic  INTERNAL  ━━━━━━━━━━

  × processing panicked: internal error: entered unreachable code: the rule is turned off, it should not step in here

  ! This diagnostic was derived from an internal Biome error. Potential bug, please report it if necessary.


.\src\path\file.ts internalError/panic  INTERNAL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 

  × processing panicked: internal error: entered unreachable code: the rule is turned off, it should not step in here

  ! This diagnostic was derived from an internal Biome error. Potential bug, please report it if necessary.


.\src\path\file.ts internalError/panic  INTERNAL  ━━━━━━━━━━━━━━━━━━━━━━━━

  × processing panicked: internal error: entered unreachable code: the rule is turned off, it should not step in here

  ! This diagnostic was derived from an internal Biome error. Potential bug, please report it if necessary.


.\src\path\file.ts internalError/panic  INTERNAL  ━━━━━━━━━━━━━━━━━━━ 

  × processing panicked: internal error: entered unreachable code: the rule is turned off, it should not step in here

  ! This diagnostic was derived from an internal Biome error. Potential bug, please report it if necessary.


.\src\path\file.ts internalError/panic  INTERNAL  ━━━━━━━━━━━━━━━━━━━━━ 

  × processing panicked: internal error: entered unreachable code: the rule is turned off, it should not step in here

  ! This diagnostic was derived from an internal Biome error. Potential bug, please report it if necessary.


.\src\path\file.ts internalError/panic  INTERNAL  ━━━━━━━━━━

  × processing panicked: internal error: entered unreachable code: the rule is turned off, it should not step in here

  ! This diagnostic was derived from an internal Biome error. Potential bug, please report it if necessary.


.\src\path\file.ts internalError/panic  INTERNAL  ━━━━━━━━━━━━━━━━━

  × processing panicked: internal error: entered unreachable code: the rule is turned off, it should not step in here

  ! This diagnostic was derived from an internal Biome error. Potential bug, please report it if necessary.


.\src\path\file.ts internalError/panic  INTERNAL  ━━━━━━━━━━

  × processing panicked: internal error: entered unreachable code: the rule is turned off, it should not step in here

  ! This diagnostic was derived from an internal Biome error. Potential bug, please report it if necessary.


.\src\path\file.ts internalError/panic  INTERNAL  ━━━━━━━━━━━━━━ 

  × processing panicked: internal error: entered unreachable code: the rule is turned off, it should not step in here

  ! This diagnostic was derived from an internal Biome error. Potential bug, please report it if necessary.


.\src\path\file.ts internalError/panic  INTERNAL  ━━━━━━━━━━━━━━━━━━━━ 

  × processing panicked: internal error: entered unreachable code: the rule is turned off, it should not step in here

  ! This diagnostic was derived from an internal Biome error. Potential bug, please report it if necessary.


.\src\path\file.ts internalError/panic  INTERNAL  ━━━━━━━━━━━ 

  × processing panicked: internal error: entered unreachable code: the rule is turned off, it should not step in here

  ! This diagnostic was derived from an internal Biome error. Potential bug, please report it if necessary.


.\src\path\file.ts internalError/panic  INTERNAL  ━━━━━━━━━━━━━━━━━━━

  × processing panicked: internal error: entered unreachable code: the rule is turned off, it should not step in here

  ! This diagnostic was derived from an internal Biome error. Potential bug, please report it if necessary.


.\src\path\file.ts internalError/panic  INTERNAL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 

  × processing panicked: internal error: entered unreachable code: the rule is turned off, it should not step in here

  ! This diagnostic was derived from an internal Biome error. Potential bug, please report it if necessary.


.\src\path\file.ts internalError/panic  INTERNAL  ━━━━━━━━━━━━━━━ 

  × processing panicked: internal error: entered unreachable code: the rule is turned off, it should not step in here

  ! This diagnostic was derived from an internal Biome error. Potential bug, please report it if necessary.


.\src\path\file.ts internalError/panic  INTERNAL  ━━━━━━━━━━━━━━ 

  × processing panicked: internal error: entered unreachable code: the rule is turned off, it should not step in here

  ! This diagnostic was derived from an internal Biome error. Potential bug, please report it if necessary.


.\src\path\file.ts internalError/panic  INTERNAL  ━━━━━━━━━━━━━━━━━ 

  × processing panicked: internal error: entered unreachable code: the rule is turned off, it should not step in here

  ! This diagnostic was derived from an internal Biome error. Potential bug, please report it if necessary.


.\src\path\file.ts internalError/panic  INTERNAL  ━━━━━━━━━━━━━━━━━ 

  × processing panicked: internal error: entered unreachable code: the rule is turned off, it should not step in here

  ! This diagnostic was derived from an internal Biome error. Potential bug, please report it if necessary.


Checked 1575 file(s) in 90ms
```
</details>

**Comment by Conaclos** [comment]
I am working on a fix that will be released at the start of next week.

A **temporary workaround** is of setting every `recommended` to false in the overrides.
Foe example:

```diff
"overrides": [
    {
      "include": ["*.spec.ts", "*.spec.tsx"],
      "linter": {
        "rules": {
+         "recommended": false,
          "performance": {
+           "recommended": false,
            "noDelete": "off"
          }
        }
      }
    }
  ]
```

**Comment by Conaclos** [comment]
This should now be fixed by the last release: 1.5.3
