### ISSUE TITLE
Formatting files even if they are ignored

### ISSUE THREAD

**Issue by SorenHolstHansen** [biomejs/biome#1504]
Say you have a simple biome config with the files section set to something like
```json
"files": {
  "ignore": "./some/file.json"
}
```
And then you open `/some/file.json` in vscode, then biome will format the file even though it is ignored.

The vscode extension should respect the `files` section when deciding to format or not

**Comment by SorenHolstHansen** [comment]
> Hey @SorenHolstHansen,
> 
> Thank you for opening this issue.
> 
> The `files.ignore` config option should be an array of paths.
> 
> ```json
> "files": {
>   "ignore": ["./some/file.json"]
> }
> ```
> 
> But there still appears to be an issue with resolving the file when specified with a leading `./`. Could you try the following:
> 
> ```json
> "files": {
>   "ignore": ["some/file.json"]
> }
> ```
> 
> Screen.Recording.2024-01-10.at.10.55.45.mov
> 
> In the meantime, I'll move this issue to the main biome repo, because this is not handled by the VS Code extension itself.

Arrrh, yeah! Forgot to make it an array in the example above, but yeah, the issue still persists

**Comment by Conaclos** [comment]
Which version of Biome are you using? The last version have a regression regarding `include`/`ignore`.

**Comment by nhedger** [comment]
> Which version of Biome are you using? The last version have a regression regarding `include`/`ignore`.

I was able to reproduce on the latest (1.5.0)

**Comment by nhedger** [comment]
There's a fair chance that https://github.com/biomejs/biome/pull/1489 will solve this issue.

**Comment by Conaclos** [comment]
This should be fixed in the last patch release (v1.5.1). Could anyone confirm that they no longer get errors?

**Comment by SorenHolstHansen** [comment]
The issue is still there for me. Looking at the release notes for 1.5.1 doesn't list #1489, so I don't think it has been added?

Also, while we are at it, I can't seem to find #1134 in the release notes anywhere as well

**Comment by ematipico** [comment]
@SorenHolstHansen I created a repository with your exact sample, and I don't understand your issue. Have you tried to restart the LSP server?

**Comment by SorenHolstHansen** [comment]
Yeah, you are right, seems to work now. I had forgotten to remove the `./` prefix
