### ISSUE TITLE
📝 Formatter produces different output on 2nd run

### ISSUE THREAD

**Issue by xxzefgh** [biomejs/biome#4383]
### Environment information

```bash
CLI:
  Version:                      1.9.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.18.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "pnpm/9.12.1"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Formatter:
  Format with errors:           false
  Indent style:                 Tab
  Indent width:                 2
  Line ending:                  Lf
  Line width:                   120
  Attribute position:           Auto
  Bracket spacing:              BracketSpacing(true)
  Ignore:                       []
  Include:                      []

JavaScript Formatter:
  Enabled:                      true
  JSX quote style:              Double
  Quote properties:             AsNeeded
  Trailing commas:              All
  Semicolons:                   Always
  Arrow parentheses:            Always
  Bracket spacing:              unset
  Bracket same line:            false
  Quote style:                  Double
  Indent style:                 unset
  Indent width:                 unset
  Line ending:                  unset
  Line width:                   unset
  Attribute position:           unset

JSON Formatter:
  Enabled:                      true
  Indent style:                 unset
  Indent width:                 unset
  Line ending:                  unset
  Line width:                   unset
  Trailing Commas:              unset

CSS Formatter:
  Enabled:                      true
  Indent style:                 unset
  Indent width:                 unset
  Line ending:                  unset
  Line width:                   unset
  Quote style:                  Double

GraphQL Formatter:
  Enabled:                      false
  Indent style:                 unset
  Indent width:                 unset
  Line ending:                  unset
  Line width:                   unset
  Bracket spacing:              unset
  Quote style:                  unset

Workspace:
  Open Documents:               0
```

### Configuration

```JSON
{
	"$schema": "https://biomejs.dev/schemas/1.9.3/schema.json",
	"organizeImports": {
		"enabled": true
	},
	"files": {
		"ignore": ["types", ".vscode", "dist", "node_modules", "./package.json"]
	},
	"formatter": {
		"enabled": true,
		"lineWidth": 120,
		"indentStyle": "tab",
		"lineEnding": "lf"
	},
	"linter": {
		"enabled": true
	}
}
```

### Playground link

https://biomejs.dev/playground/?lineWidth=120&code=aQBtAHAAbwByAHQAIAB7AGkAbgB0AGUAZwBlAHIALAAgAHAAZwBUAGEAYgBsAGUAfQAgAGYAcgBvAG0AIAAiAGQAcgBpAHoAegBsAGUALQBvAHIAbQAvAHAAZwAtAGMAbwByAGUAIgA7AAoACgBjAG8AbgBzAHQAIABlAHgAYQBtAHAAbABlACAAPQAgAHAAZwBUAGEAYgBsAGUAKAAiAGUAeABhAG0AcABsAGUAIgAsACAAewAKAAkAaQBkADoAIABpAG4AdABlAGcAZQByACgAKQAuAHAAcgBpAG0AYQByAHkASwBlAHkAKAApAC4AZwBlAG4AZQByAGEAdABlAGQAQgB5AEQAZQBmAGEAdQBsAHQAQQBzAEkAZABlAG4AdABpAHQAeQAoAHsAIABuAGEAbQBlADoAIAAiAGUAeABhAG0AcABsAGUAXwBpAGQAXwBzAGUAcQAiACwAIABzAHQAYQByAHQAVwBpAHQAaAA6ACAAMQAsACAAaQBuAGMAcgBlAG0AZQBuAHQAOgAgADEALAAgAG0AaQBuAFYAYQBsAHUAZQA6ACAAMQAsACAAbQBhAHgAVgBhAGwAdQBlADoAIAAyADEANAA3ADQAOAAzADYANAA3ACwAIABjAGEAYwBoAGUAOgAgADEAIAB9ACkACgB9ACkAOwAKAA%3D%3D

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by xxzefgh** [comment]
This is the 2nd playground link. I've pasted output from first one in the editor:

https://biomejs.dev/playground/?lineWidth=120&code=aQBtAHAAbwByAHQAIAB7ACAAaQBuAHQAZQBnAGUAcgAsACAAcABnAFQAYQBiAGwAZQAgAH0AIABmAHIAbwBtACAAIgBkAHIAaQB6AHoAbABlAC0AbwByAG0ALwBwAGcALQBjAG8AcgBlACIAOwAKAAoAYwBvAG4AcwB0ACAAZQB4AGEAbQBwAGwAZQAgAD0AIABwAGcAVABhAGIAbABlACgAIgBlAHgAYQBtAHAAbABlACIALAAgAHsACgAJAGkAZAA6ACAAaQBuAHQAZQBnAGUAcgAoACkACgAJAAkALgBwAHIAaQBtAGEAcgB5AEsAZQB5ACgAKQAKAAkACQAuAGcAZQBuAGUAcgBhAHQAZQBkAEIAeQBEAGUAZgBhAHUAbAB0AEEAcwBJAGQAZQBuAHQAaQB0AHkAKAB7AAoACQAJAAkAbgBhAG0AZQA6ACAAIgBlAHgAYQBtAHAAbABlAF8AaQBkAF8AcwBlAHEAIgAsAAoACQAJAAkAcwB0AGEAcgB0AFcAaQB0AGgAOgAgADEALAAKAAkACQAJAGkAbgBjAHIAZQBtAGUAbgB0ADoAIAAxACwACgAJAAkACQBtAGkAbgBWAGEAbAB1AGUAOgAgADEALAAKAAkACQAJAG0AYQB4AFYAYQBsAHUAZQA6ACAAMgAxADQANwA0ADgAMwA2ADQANwAsAAoACQAJAAkAYwBhAGMAaABlADoAIAAxACwACgAJAAkAfQApACwACgB9ACkAOwAKAA%3D%3D

**Comment by ematipico** [comment]
It seems this is fixed

**Comment by vzd3v** [comment]
This still reproduces on the latest release **2.4.16** — including the original `drizzle-kit` snippet from the top of this issue: pass 1 expands the member chain, pass 2 collapses it back inline (pass 3 is stable). So `format`/`check` is not idempotent for member chains whose final call argument is an object literal.

Filed a fresh report with a minimal repro and version details: #10531. Might be worth reopening or re-linking if this was closed prematurely.
