### ISSUE TITLE
💅 V2 processing panicked: called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by hoangtrung99** [biomejs/biome#5458]
### Environment information

```bash
CLI:
  Version:                      2.0.0-beta.1
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  NO_COLOR:                     unset
  TERM:                         xterm-256color
  JS_RUNTIME_VERSION:           v20.12.2
  JS_RUNTIME_NAME:              node
  NODE_PACKAGE_MANAGER:         pnpm/9.12.3

Biome Configuration:
  Status:                       Loaded successfully
  Path:                         /Users/hoangtrung/Local/Work/solashi/irrc/front/biome.json
  Formatter enabled:            true
  Linter enabled:               true
  Assist enabled:               true
  VCS enabled:                  false

Linter:
  JavaScript enabled:           unset
  JSON enabled:                 unset
  CSS enabled:                  unset
  GraphQL enabled:              unset
  Recommended:                  unset
  Enabled rules:
    a11y/noAccessKey
    a11y/noAriaHiddenOnFocusable
    a11y/noAriaUnsupportedElements
    a11y/noAutofocus
    a11y/noBlankTarget
    a11y/noDistractingElements
    a11y/noHeaderScope
    a11y/noInteractiveElementToNoninteractiveRole
    a11y/noLabelWithoutControl
    a11y/noNoninteractiveElementToInteractiveRole
    a11y/noNoninteractiveTabindex
    a11y/noPositiveTabindex
    a11y/noRedundantAlt
    a11y/noRedundantRoles
    a11y/noSvgWithoutTitle
    a11y/useAltText
    a11y/useAnchorContent
    a11y/useAriaActivedescendantWithTabindex
    a11y/useAriaPropsForRole
    a11y/useButtonType
    a11y/useFocusableInteractive
    a11y/useGenericFontNames
    a11y/useHeadingContent
    a11y/useHtmlLang
    a11y/useIframeTitle
    a11y/useKeyWithClickEvents
    a11y/useKeyWithMouseEvents
    a11y/useMediaCaption
    a11y/useSemanticElements
    a11y/useValidAnchor
    a11y/useValidAriaProps
    a11y/useValidAriaRole
    a11y/useValidAriaValues
    a11y/useValidLang
    complexity/noAdjacentSpacesInRegex
    complexity/noBannedTypes
    complexity/noEmptyTypeParameters
    complexity/noExtraBooleanCast
    complexity/noStaticOnlyClass
    complexity/noThisInStatic
    complexity/noUselessCatch
    complexity/noUselessConstructor
    complexity/noUselessEmptyExport
    complexity/noUselessFragments
    complexity/noUselessLabel
    complexity/noUselessLoneBlockStatements
    complexity/noUselessRename
    complexity/noUselessSwitchCase
    complexity/noUselessTernary
    complexity/noUselessThisAlias
    complexity/noUselessTypeConstraint
    complexity/noWith
    complexity/useArrowFunction
    complexity/useFlatMap
    complexity/useLiteralKeys
    complexity/useOptionalChain
    complexity/useRegexLiterals
    complexity/useSimpleNumberKeys
    correctness/noChildrenProp
    correctness/noConstAssign
    correctness/noConstantCondition
    correctness/noConstructorReturn
    correctness/noEmptyCharacterClassInRegex
    correctness/noEmptyPattern
    correctness/noFlatMapIdentity
    correctness/noGlobalObjectCalls
    correctness/noInnerDeclarations
    correctness/noInvalidBuiltinInstantiation
    correctness/noInvalidConstructorSuper
    correctness/noInvalidDirectionInLinearGradient
    correctness/noInvalidGridAreas
    correctness/noInvalidPositionAtImportRule
    correctness/noInvalidUseBeforeDeclaration
    correctness/noNonoctalDecimalEscape
    correctness/noPrecisionLoss
    correctness/noPrivateImports
    correctness/noSelfAssign
    correctness/noSetterReturn
    correctness/noStringCaseMismatch
    correctness/noSwitchDeclarations
    correctness/noUnknownFunction
    correctness/noUnknownMediaFeatureName
    correctness/noUnknownProperty
    correctness/noUnknownUnit
    correctness/noUnmatchableAnbSelector
    correctness/noUnreachable
    correctness/noUnreachableSuper
    correctness/noUnsafeFinally
    correctness/noUnsafeOptionalChaining
    correctness/noUnusedImports
    correctness/noUnusedLabels
    correctness/noUselessContinue
    correctness/noVoidElementsWithChildren
    correctness/noVoidTypeReturn
    correctness/useIsNan
    correctness/useValidForDirection
    correctness/useYield
    nursery/noImportCycles
    performance/noAccumulatingSpread
    security/noDangerouslySetInnerHtml
    security/noDangerouslySetInnerHtmlWithChildren
    security/noGlobalEval
    style/noArguments
    style/noCommaOperator
    style/noInferrableTypes
    style/noParameterAssign
    style/noUnusedTemplateLiteral
    style/noUselessElse
    style/useAsConstAssertion
    style/useConst
    style/useDefaultParameterLast
    style/useEnumInitializers
    style/useExponentiationOperator
    style/useExportType
    style/useImportType
    style/useLiteralEnumMembers
    style/useNodejsImportProtocol
    style/useNumberNamespace
    style/useNumericLiterals
    style/useSelfClosingElements
    style/useShorthandFunctionType
    style/useSingleVarDeclarator
    style/useTemplate
    suspicious/noApproximativeNumericConstant
    suspicious/noAssignInExpressions
    suspicious/noAsyncPromiseExecutor
    suspicious/noCatchAssign
    suspicious/noClassAssign
    suspicious/noCommentText
    suspicious/noCompareNegZero
    suspicious/noConfusingLabels
    suspicious/noConfusingVoidType
    suspicious/noConstEnum
    suspicious/noControlCharactersInRegex
    suspicious/noDebugger
    suspicious/noDoubleEquals
    suspicious/noDuplicateAtImportRules
    suspicious/noDuplicateCase
    suspicious/noDuplicateClassMembers
    suspicious/noDuplicateFontNames
    suspicious/noDuplicateJsxProps
    suspicious/noDuplicateObjectKeys
    suspicious/noDuplicateParameters
    suspicious/noDuplicateSelectorsKeyframeBlock
    suspicious/noEmptyBlock
    suspicious/noEmptyInterface
    suspicious/noExplicitAny
    suspicious/noExtraNonNullAssertion
    suspicious/noFallthroughSwitchClause
    suspicious/noFunctionAssign
    suspicious/noGlobalAssign
    suspicious/noGlobalIsFinite
    suspicious/noGlobalIsNan
    suspicious/noImplicitAnyLet
    suspicious/noImportAssign
    suspicious/noImportantInKeyframe
    suspicious/noLabelVar
    suspicious/noMisleadingCharacterClass
    suspicious/noMisleadingInstantiator
    suspicious/noMisrefactoredShorthandAssign
    suspicious/noPrototypeBuiltins
    suspicious/noRedeclare
    suspicious/noRedundantUseStrict
    suspicious/noSelfCompare
    suspicious/noShadowRestrictedNames
    suspicious/noShorthandPropertyOverrides
    suspicious/noSparseArray
    suspicious/noSuspiciousSemicolonInJsx
    suspicious/noThenProperty
    suspicious/noUnsafeDeclarationMerging
    suspicious/noUnsafeNegation
    suspicious/useDefaultSwitchClauseLast
    suspicious/useGetterReturn
    suspicious/useIsArray
    suspicious/useNamespaceKeyword
    suspicious/useValidTypeof

Workspace:
  Open Documents:               0
```

### Rule name

internalError/panic

### Playground link

https://biomejs.dev/playground/?code=aQBtAHAAbwByAHQAIABSAGUAYQBjAHQAIABmAHIAbwBtACAAJwByAGUAYQBjAHQAJwAKAGkAbQBwAG8AcgB0ACAAewAgAHUAcwBlAEQAZQBlAHAAQwBvAG0AcABhAHIAZQBNAGUAbQBvAGkAegBlACAAfQAgAGYAcgBvAG0AIAAnAC4ALwB1AHMAZQBEAGUAZQBwAEMAbwBtAHAAYQByAGUATQBlAG0AbwBpAHoAZQAnAAoACgAvACoAKgAKACAAKgAgAEEAIABjAHUAcwB0AG8AbQAgAGgAbwBvAGsAIAB0AGgAYQB0ACAAcAByAG8AdgBpAGQAZQBzACAAZABlAGUAcAAgAGMAbwBtAHAAYQByAGkAcwBvAG4AIABmAG8AcgAgAHUAcwBlAE0AZQBtAG8AIABkAGUAcABlAG4AZABlAG4AYwBpAGUAcwAuAAoAIAAqACAAVABoAGkAcwAgAGgAbwBvAGsAIABpAHMAIAB1AHMAZQBmAHUAbAAgAHcAaABlAG4AIAB5AG8AdQAgAG4AZQBlAGQAIAB0AG8AIABtAGUAbQBvAGkAegBlACAAdgBhAGwAdQBlAHMAIAB3AGkAdABoACAAYwBvAG0AcABsAGUAeAAgAG8AYgBqAGUAYwB0ACAAZABlAHAAZQBuAGQAZQBuAGMAaQBlAHMALgAKACAAKgAKACAAKgAgAEAAdABlAG0AcABsAGEAdABlACAAVAAgAC0AIABUAGgAZQAgAHQAeQBwAGUAIABvAGYAIAB0AGgAZQAgAG0AZQBtAG8AaQB6AGUAZAAgAHYAYQBsAHUAZQAKACAAKgAgAEAAcABhAHIAYQBtACAAewAoACkAIAA9AD4AIABUAH0AIABmAGEAYwB0AG8AcgB5ACAALQAgAFQAaABlACAAZgB1AG4AYwB0AGkAbwBuACAAdABoAGEAdAAgAHIAZQB0AHUAcgBuAHMAIAB0AGgAZQAgAHYAYQBsAHUAZQAgAHQAbwAgAG0AZQBtAG8AaQB6AGUACgAgACoAIABAAHAAYQByAGEAbQAgAHsAdQBuAGsAbgBvAHcAbgBbAF0AfQAgAGQAZQBwAGUAbgBkAGUAbgBjAGkAZQBzACAALQAgAEEAcgByAGEAeQAgAG8AZgAgAGQAZQBwAGUAbgBkAGUAbgBjAGkAZQBzACAAdABoAGEAdAAgAHcAaQBsAGwAIABiAGUAIABjAG8AbQBwAGEAcgBlAGQAIABkAGUAZQBwAGwAeQAKACAAKgAgAEAAcgBlAHQAdQByAG4AcwAgAHsAVAB9ACAAVABoAGUAIABtAGUAbQBvAGkAegBlAGQAIAB2AGEAbAB1AGUACgAgACoACgAgACoAIABAAGUAeABhAG0AcABsAGUACgAgACoAIABgAGAAYAB0AHMAeAAKACAAKgAgAGMAbwBuAHMAdAAgAG0AZQBtAG8AaQB6AGUAZABWAGEAbAB1AGUAIAA9ACAAdQBzAGUARABlAGUAcABDAG8AbQBwAGEAcgBlAE0AZQBtAG8AKAAKACAAKgAgACAAIAAoACkAIAA9AD4AIABjAG8AbQBwAHUAdABlAEUAeABwAGUAbgBzAGkAdgBlAFYAYQBsAHUAZQAoAGEALAAgAGIAKQAsAAoAIAAqACAAIAAgAFsAYQAsACAAYgBdAAoAIAAqACAAKQAKACAAKgAgAGAAYABgAAoAIAAqAAoAIAAqACAAQABzAGUAZQAgAHsAQABsAGkAbgBrACAAaAB0AHQAcABzADoALwAvAHIAZQBhAGMAdAAuAGQAZQB2AC8AcgBlAGYAZQByAGUAbgBjAGUALwByAGUAYQBjAHQALwB1AHMAZQBNAGUAbQBvAH0ACgAgACoALwAKAGUAeABwAG8AcgB0ACAAZgB1AG4AYwB0AGkAbwBuACAAdQBzAGUARABlAGUAcABDAG8AbQBwAGEAcgBlAE0AZQBtAG8APABUAD4AKAAKACAAIABmAGEAYwB0AG8AcgB5ADoAIAAoACkAIAA9AD4AIABUACwACgAgACAAZABlAHAAZQBuAGQAZQBuAGMAaQBlAHMAOgAgAHUAbgBrAG4AbwB3AG4AWwBdAAoAKQA6ACAAVAAgAHsACgAgACAAYwBvAG4AcwB0ACAAbQBlAG0AbwBpAHoAZQBkAEQAZQBwAHMAIAA9ACAAdQBzAGUARABlAGUAcABDAG8AbQBwAGEAcgBlAE0AZQBtAG8AaQB6AGUAKABkAGUAcABlAG4AZABlAG4AYwBpAGUAcwApAAoACgAKACAAIAByAGUAdAB1AHIAbgAgAFIAZQBhAGMAdAAuAHUAcwBlAE0AZQBtAG8APABUAD4AKABmAGEAYwB0AG8AcgB5ACwAIABtAGUAbQBvAGkAegBlAGQARABlAHAAcwApAAoAfQAKAA%3D%3D

### Expected result

Expected no errors, but in reality

<img width="1592" alt="Image" src="https://github.com/user-attachments/assets/0d63d4c0-a4c3-496f-a365-3c7152fd8400" />

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
@hoangtrung99 

The rule assumes that the second argument is a readonly array. Can you explain why your snippet doesn't use an array? Even the react docs shows that you need to pass an array.

**Comment by ematipico** [comment]
`React.DependecyList` is resolved to an array.

![Image](https://github.com/user-attachments/assets/e5d72c77-b1dc-42d4-b33e-a09877327187)

I am closing because this is a user error.

**Comment by hoangtrung99** [comment]
> `React.DependecyList` is resolved to an array.
> 
> ![Image](https://github.com/user-attachments/assets/e5d72c77-b1dc-42d4-b33e-a09877327187)
> 
> I am closing because this is a user error.

@ematipico 
Wait, however, the error `internalError/panic` still occurs.

**Comment by siketyan** [comment]
I think we can at least add a diagnostic instead of panic.

**Comment by siketyan** [comment]
As a prior art, eslint-plugin-react-hooks reports a problem when it found a dependency list which is not an array literal:
https://github.com/facebook/react/blob/8ac25e5201579c65d115d91c211ac719a235d982/packages/eslint-plugin-react-hooks/src/rules/ExhaustiveDeps.ts#L718-L727

**Comment by ematipico** [comment]
That's fair, we shouldn't panic!

**Comment by Conaclos** [comment]
Generally we should not panic. This looks like a bad user experience.

**Comment by vhfmag** [comment]
sorry for posting on a closed issue, but are there any plans to release a new beta version including this fix? I'm looking into adopting the beta version for my company's codebase but this is currently blocking us. thanks!
