### ISSUE TITLE
🐛 internalError/io when using CLI format

### ISSUE THREAD

**Issue by ThaisRobba** [biomejs/biome#5697]
### Environment information

```block
CLI:
  Version:                      2.0.0-beta.1
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  NO_COLOR:                     unset
  TERM:                         xterm-256color
  JS_RUNTIME_VERSION:           v22.14.0
  JS_RUNTIME_NAME:              node
  NODE_PACKAGE_MANAGER:         npm/10.9.2

Biome Configuration:
  Status:                       Loaded successfully
  Path:                         /Users/thais/Documents/frontend-monorepo/biome.json
  Formatter enabled:            true
  Linter enabled:               true
  Assist enabled:               true
  VCS enabled:                  true

Workspace:
  Open Documents:               0
```

### What happened?

When running the format command targeting a file that is already formatted OR is a file within a subfolder, I get a `No such file or directory (os error 2)`.

#### Case 1

Given a `biome.json` file at the root level and with incorrect formatting:

`npx biome format biome.json --write` works ✅ 
`npx biome format ./biome.json --write` works but throws an error ❌ 

#### Case 2

Given a `my-file.ts` at subfolder `./libs`:

`npx biome format ./libs/my-file.ts --write` does not work and throws an error ❌ 

### Expected result

It should format files in sub-folders and not throw an error when there is nothing to format.

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### Reproduction

https://github.com/ThaisRobba/biome-repro-1744988212423

**Comment by ematipico** [comment]
What's the error that you receive?

**Comment by ematipico** [comment]
I suppose the issue is caused by the non-normalisation of the paths

**Comment by 1yasa** [comment]
same error.

**Comment by ThaisRobba** [comment]
Created reproduction repo: https://github.com/ThaisRobba/biome-repro-1744988212423

**Comment by 1yasa** [comment]
Solved by `"biome": "biome format . --write --staged"`

**Comment by ThaisRobba** [comment]
@1yasa that does not solve the case in the reproduction example

**Comment by 1yasa** [comment]
> [@1yasa](https://github.com/1yasa) that does not solve the case in the reproduction example

It`s my project resolution 😅

**Comment by siketyan** [comment]
@ThaisRobba The formatter seems disabled to run on the file. I could run the formatter successfully after edited biome.json:

```diff
diff --git a/biome.json b/biome.json
index 46a5eaf..ef0576a 100644
--- a/biome.json
+++ b/biome.json
@@ -14,7 +14,7 @@
     "lineWidth": 120,
     "formatWithErrors": true,
     "indentWidth": 2,
-    "includes": ["./apps/**", "./libs/**"]
+    "includes": ["src/apps/**", "src/libs/**"]
   },
   "linter": {
     "enabled": true,
```

**Comment by ThaisRobba** [comment]
@siketyan Ah, nice catch! Great work with that PR ^^ I'm closing this now..
