### ISSUE TITLE
🐛 Memory leak in `biome.exe`

### ISSUE THREAD

**Issue by Profesor08** [biomejs/biome#6784]
### VS Code version

1.202.0

### Extension version

3.1.0

### Biome version

2.1.0

### Operating system

- [x] Windows
- [ ] macOS
- [ ] Linux

### Description

Found performance issues on my PC, randomly checked task manager, and found `biome.exe` uses 23 GB of memory, and growing little by little. The only solution is to close all vscode instances.

https://github.com/user-attachments/assets/20980467-533c-4b7a-8bef-43782b5807f6

### Steps to reproduce

I don't know, after restart it looks ok, but I don't know for how long

### Expected behavior

To not eat all my memory and to look like

<img width="796" height="124" alt="Image" src="https://github.com/user-attachments/assets/617e529d-68f6-4862-827c-c3acf3433265" />

### Does this issue occur when using the CLI directly?

No

### Logs

```plain text

```

**Comment by eMerzh** [comment]
looks like https://github.com/biomejs/biome/issues/6797 no?

**Comment by Profesor08** [comment]
@eMerzh can't say exactly, because it happened after I had updated biome to latest version. And didn't observed something like that earlier.

Currently I'm monitoring resources, used by biome, and they are consumed in normal range. Also manualy configured `files.includes`

```json
{
  "files": {
    "includes": [
      "**",
      "!**/node_modules/**",
      "!**/public/**",
      "!**/.wrangler/**",
      "!**/dist/**",
      "!**/icons/**",
      "!**/patches/**",
      "!**/*.css",
      "!**/*.scss"
    ]
  },
}
```

**Comment by ematipico** [comment]
Memory leaks belong to core :)

However, they are hard to reproduce, so we need users to pin point which files are causing the slowness.

**Comment by SeraNox123** [comment]
Tried to reproduce, as I'm seeing the same issue — pretty sure it's due to the lint/correctness/noPrivateImports rule. Try disabling and enabling it and testing memory usage.
Using PHPStorm 2025.1.3, Biome plugin version 1.8.1 and Biome version 2.1.1

**Comment by SeraNox123** [comment]
Those rules also cause same memory leak:
lint/correctness/noUndeclaredDependencies
lint/correctness/useImportExtensions

**Comment by Profesor08** [comment]
1. Is the `node_modules` folder excluded by default?
2. Will a config like `"include": ["src/**/*.js"]` search for files only in `src`?
3. Will a config like `"include": ["**", "!**/*.test.js", "**/special.test.js", "!test"]` exclude `node_modules` from the search?

**Comment by siketyan** [comment]
The scanner scans entire the project even if it's not included in the config, except a few hard-coded denylist. Files in node_modules are also scanned. Behaviour of the scanner changes by turning on any of the "project rules" - that requires a detailed module graph created by the scanner. It's possible that a specific file scanned by the scanner causes memory leak as an edge case.

**Comment by ematipico** [comment]
It's fantastic that we identified the rules that cause the problem; however, we need a repository because as @siketyan mentioned, there might be some dependencies out there that are causing weird things to Biome.

**Comment by Profesor08** [comment]
Sample project with config and dependencies

[biome-repro-1752044022371.zip](https://github.com/user-attachments/files/21136831/biome-repro-1752044022371.zip)

**Comment by blutorange** [comment]
2 more data points:

* I can reproduce the issue on my machine with the sample project from Profesor08. It happens once I open VSCode, even without installing any node_modules.
* It also happens on our internal project when I just run the linter via the CLI. So it's not an issue with the VSCode plugin (`biome lint --config-path ../../../.. src __tests__ @types`)

**Comment by arendjr** [comment]
@blutorange are you also using Windows? I just tried the same reproduction and it doesn't trigger anything weird for me, neither through the CLI nor with the VS Code extension. Didn't matter whether `node_modules` were installed either.

Btw, we've created a page to help people investigate slowness issues: https://biomejs.dev/guides/investigate-slowness/

If you could try the suggestions there, we may also find something more concrete to act on.

**Comment by paleo** [comment]
Same issue in Ubuntu 24.04 and Biome 2.1.1 on [this monorepo](https://gitlab.com/paroi/opensource/paroicms). I just reverted it to Biome 2.0.6. But it's easy to reproduce.

Also the behavior is not the same if you upgrade Biome from 2.0.6 to 2.1.1, or if you remove node_modules directories & lock file before installing 2.1.1.

**Comment by samhh** [comment]
I'm also seeing issues with Biome consistent with this for the first time on macOS since updating to 2.1.

**Comment by PAXANDDOS** [comment]
I'm also here to report this issue, hope it's gonna be useful.

It first started happening after the v2 release. I couldn't capture the usage, but my PC fans were occasionally speeding up to the point it sounded like my old gaming laptop. I think RAM usage then was big but not too much, around 3GB?

Now, since v2.1, I struggled for 5 minutes to just open my task manager because it would always stop responding, but when I did, I saw that:

<img width="776" height="236" alt="Image" src="https://github.com/user-attachments/assets/dd738505-e019-4394-a051-5f852724900a" />  

There were several biome processes. I'm just fuming by the fact that my 32GB RAM stick was filled to the brim with only biome! And 1GB SSD usage as well?? My project wasn't even on SSD

---

Windows 11 Pro (Version 10.0.26100 Build 26100)
AMD Ryzen 7 5800X3D

Biome version: 2.1.1
Extension version: 3.1.0
VSCode version: 1.99.3 (Cursor 1.2.2)

Monorepo setup (Turborepo):
- [biome.json](https://github.com/user-attachments/files/21142554/biome.json) (root)
- [apps/dashboard/biome.json](https://github.com/user-attachments/files/21142563/biome.json) (nextjs)
- [apps/tv/biome.json](https://github.com/user-attachments/files/21142568/biome.json) (svelte)
- [packages/db/biome.json](https://github.com/user-attachments/files/21142575/biome.json)

The moment I noticed high RAM usage, I was working in the Next.js app, but it had previously happened in different scenarios as well. For example, I left my PC idle for an hour or more, came back to 100% ram usage 😕 Rolling back to 2.0.6 for now

**Comment by arendjr** [comment]
@paleo wrote:

> Also the behavior is not the same if you upgrade Biome from 2.0.6 to 2.1.1, or if you remove `node_modules` directories & lock file before installing 2.1.1.

Are you saying it happens when you upgrade from 2.0.6 to 2.1.1, but it does **not** happen when you first remove `node_modules` and the lock file, and _then_ install 2.1.1? If that is the case, what package manager are you using? This might point to something weird depending on the order of installation, and maybe it could be explained by Biome tripping over some symlinks in one scenario, but not another?

**Comment by blutorange** [comment]
> are you also using Windows? I just tried the same reproduction and it doesn't trigger anything weird for me, neither through the CLI nor with the VS Code extension. Didn't matter whether node_modules were installed either.

@arendjr Funny enough, I tried the simple repro project again and now it behaves, no memory leak anymore. But for reference, I'm on Linux (Linux mobil-xm-00601 6.14.0-23-generic # 23-Ubuntu SMP PREEMPT_DYNAMIC Fri Jun 13 23:02:20 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux, Ubuntu 25.04)

> Btw, we've created a page to help people investigate slowness issues: https://biomejs.dev/guides/investigate-slowness/

That's a great help! It's still slow on our larger internal project. So I tried the debugging logs. In short, the tracing.json is 19474 lines long and it's all from `update_module_graph`. After that, no more entries and biome starts using up all available RAM.

Now that's a lot files, and includes files that we do not want to lint, such as e.g. build artifacts like

> /home/user/git/project/reporting/target/site/jacoco-aggregate/our-project/com.example/SomeClass.java.html 

I checked out a branch from before the 2.x update and ran `yarn biome lint` with the `--verbose` command. It just outputs a few (124) source files that we actually want to lint. I did not manually change config files, but I ran `yarn exec biome migrate --write` as suggested in the migration guide when I updated to 2.x.

---

So I think at least part of the issue is: After the 1.x -> 2.x update, biome scans way more files than it used to before, which requires more RAM and CPU.

Previously, we only had a few excludes in our `biome.json` and specified the files to scan via the command line, e.g.:

```
yarn biome lint --config-path ../../../.. src __tests__ @types
```

After the update, the automatic migrator changed our excludes to `"includes": ["**", "!**/node_modules/**", ...]`. Even with the folders specified on the CLI, biome now seems to read all files matching that glob.

With biome 2.x, I tried limiting the files to include, but it kept processing all files such as build artifact. Now I finally found 1 configuration that works.

* In the root `biome.json`, use `"files": { "includes": [] }`. This stops biome from including various build artifact we don't want.
* In the sub `my-project/src/main/web/biome.json`, I add the folder I previously specified via the command line: `includes": ["src/**", "__tests__/**","@types/**"]`

With that, I can run the `yarn run biome lint` and it now works as before, and it's fast : )

**Comment by paleo** [comment]
> Are you saying it happens when you upgrade from 2.0.6 to 2.1.1, but it does not happen

I think it happened in both cases. I'm not sure. The linter errors are not the same in the CI so there is something unusual in the dependencies. I observed a problem related to [this one](https://github.com/biomejs/biome/issues/6801#issuecomment-3051385802):

> Another weird thing is that our CI (Github Actions, Ubuntu runners) does work well. Bit slower (3s instead of 1s) but successful. I can reproduce it locally on my ubuntu + windows machine though.

CI/local desynchro and memory leak are probably separate issues, just beware because you don't reproduce all the bugs by cloning a brand new repo.

**Comment by bangonkali** [comment]
Same here, but in addition to memory related issue there seems to be disk related issue at least on mine as well.

```sh
$ biome --version
Version: 2.1.1
```

**Relevant references:**

1. [biome.json](https://github.com/user-attachments/files/21147912/biome.json)
1. [package.json](https://github.com/user-attachments/files/21147919/package.json)

**with Biome ON:**

Both Memory and Disk usage are maxed out.

<img width="200"  alt="Image" src="https://github.com/user-attachments/assets/266f673b-7dba-4295-a5b0-b503faec5b50" />

<img width="200"  alt="Image" src="https://github.com/user-attachments/assets/9c70b73b-dfdd-498e-a00d-d6a70e7e601b" />

<img width="200"  alt="Image" src="https://github.com/user-attachments/assets/6dd6659b-cc29-4e0e-901a-8b4a25b9b0a4" />

**with Biome Off:**

Both Memory and Disk normalize.

<img width="200"  alt="Image" src="https://github.com/user-attachments/assets/8a0a1b2a-e135-456d-882a-b6100a0e985e" />

<img width="200"  alt="Image" src="https://github.com/user-attachments/assets/7168029d-f8c9-4b5b-9bb9-e47421e3052b" />

<img width="200"  alt="Image" src="https://github.com/user-attachments/assets/0f898fe6-80e2-4cff-b0f0-4504de9a5bb4" />

**Comment by blutorange** [comment]
@bangonkali Your `biome.json` contains `"includes": "**"`, just like mine did after the migration from 1.x -> 2.x. Perhaps try `npx biome lint --verbose` to see a list of files that biome processes, I suspect that includes `node_modules` and `dist` etc. folders. Or if that command never finishes, try the command from the suggested [https://biomejs.dev/guides/investigate-slowness/](guides/investigate-slowness) to get a `tracing.json` with all files that biome tried to load.

CPU / mem usage went back to normal for me after I made sure biome only loads my source files.

Perhaps like this?

```json
    "includes": [
      "src/**",
      "!src/hooks/**",
      "!src/components/ui/use-toast.ts",
      "!src/components/ui/use-mobile.ts",
      "!src/**/*.generated.d.ts",
      "!src/**/*.gen.ts"
    ]

```

**Comment by EvHaus** [comment]
Just wanted to add that I'm running into this too on MacOS, so it's not Windows specific. Both CPU and Memory usage spiked to a point where the whole machine locked up. Had to do a hard reset.

Rolling back to 2.0.6 makes the issue go away.

**Comment by Jungzl** [comment]
when in 1.x, my biome config is:
```json
  "files": {
    "ignore": ["**/*/dist", "**/*/build"],
  },
```

after upgrade to 2.x and run `pnpm exec biome migrate --write`, it becomes:
```json
  "files": {
    "includes": ["**", "!**/*/dist", "!**/*/build"],
  },
```

and if you run `npx biome check --verbose`, it actually not ignore dist files:

<img width="131" height="831" alt="Image" src="https://github.com/user-attachments/assets/6b597e9d-dc05-4dc1-8e47-2071b4642e3d" />

and if I run `vite build` then `vite preview`, it bloats my pc

so I manually modified config to:
```json
  "files": {
    "includes": ["**", "!dist", "!build"],
  },
```

no more dist files:

<img width="74" height="184" alt="Image" src="https://github.com/user-attachments/assets/adc777a8-7d3a-4d95-9427-81b79e4b01ec" />

well, now both Disk and Memory usage are normal like before.

so maybe it is the glob?

**Comment by Profesor08** [comment]
It happened again, with updated config, where I had excluded manually all directories.

```json
  "files": {
    "includes": [
      "**",
      "!**/node_modules/**",
      "!**/*.css",
      "!**/*.scss",
      "!**/public/**",
      "!**/.wrangler/**",
      "!**/dist/**",
      "!**/icons/**",
      "!**/patches/**"
    ]
  },
```

<img width="845" height="146" alt="Image" src="https://github.com/user-attachments/assets/83160da1-67f1-4431-919c-bd1de6773196" />

May be it somehow not respecting rules or some issue with glob patters.

And now, I'm be able to reproduce this:

1. Open project in vscode
2. Wait until everithong starts and initialized
3. Run build process, it cleans `dist` directory and outputs new files
4. biome.exe starts to eat memory

 Also It happens if I set empty array

```json
  "files": {
    "includes": []
  },
```

Also if I set only one directory to check

```json
  "files": {
    "includes": ["./src/**"]
  },
```

**Comment by ghost** [comment]
<img width="1213" height="199" alt="Image" src="https://github.com/user-attachments/assets/a7fed29b-f2c9-4cbe-b9aa-01526b2f4c4d" />

This happened after updating from `"@biomejs/biome": "2.0.6"` to `"@biomejs/biome": "2.1.1"`

so downgrading to `@biomejs/biome": "2.0.6"`  fixed my problem.

**Comment by ematipico** [comment]
For people coming here, **pasting your screenshots doesn't provide more information than we already have**. Since many of your repositories are private, we created this guide https://github.com/biomejs/biome/issues/guides/investigate-slowness that you can follow, and you should be able to triage and share information with us, so we can debug it further. 

If you can't, don't want to share information that can help us to pin-point the cause of the leaks, I suggest to add a 👍 to the issue to increase awareness. 

@Profesor08 can you please provide a minimal reproduction with us? It's been two days, and we're still waiting for that. We are **eager** to fix the problem, but  if we can't replicate it, our hands are tight.

**Comment by dmythro** [comment]
Yeah, just had similar issue on macOS: noticed `biome` process uses more and more RAM/CPU on every route built (seen 12 GB RAM and still going up, and at least one core of my M4 CPU usage). 

Forgot to ignore modules and generated files in my Biome config, configured like this and seems fine so far:

```json
  "files": {
    "ignoreUnknown": true,
    "includes": ["**", "!.next", "!node_modules"]
  },
```

Yes, proper configuration is important, but still I don't think a small Next.js app should feed Biome as much, didn't see this happening before v2.1 when I was just including all files and ignoring unknown before.

**Comment by ematipico** [comment]
@dmythro if you remove `node_modules`, does Biome go nuts with the memory?

**Comment by Profesor08** [comment]
@ematipico there is one more reproduction, same config as previous, but with bundler

[biome-memory-leak.zip](https://github.com/user-attachments/files/21163351/biome-memory-leak.zip)

1. `npm i`
2. `npm run build`
3. memory consumption is growing

**Comment by ematipico** [comment]
@Profesor08 

This reproduction https://github.com/biomejs/biome/issues/6784#issuecomment-3057352400: I tried it and here the result:
- no memory leaks
- no CPU usage madness
- the reproduction doesn't ignore `dist`, so after the build the files that are generated are checked

This reproduction https://github.com/biomejs/biome/issues/6784#issuecomment-3051411862: I tried it and here the result:
- no memory leaks
- no CPU usage madness
- the `dist` folder is correctly ignored, so the check command doesn't check unwanted folders

**Comment by ematipico** [comment]
@bangonkali I tried your reproduction here https://github.com/biomejs/biome/issues/6784#issuecomment-3053543741

- no leaks
- no CPU madness
- I have no info about the CLI
- The code editor behaves correctly

**Comment by Profesor08** [comment]
There is live, how it works

https://github.com/user-attachments/assets/a210f959-7858-4832-b54c-7b97caaef226

It is enought to modify one file in ignored `dist` directory

https://github.com/user-attachments/assets/66370212-800c-43c9-a349-bd0f5442d32f

**Comment by Profesor08** [comment]
May be it is somehow related to how biome `lsp-proxy` works in vscode extension?

**Comment by dmythro** [comment]
> @dmythro if you remove `node_modules`, does Biome go nuts with the memory? 

As I've been checking recently with my configuration above, everything seems fine so far. Without it, every route render or re-render on change spiked with more and more RAM used by `biome` process (while `next dev` is running). I use the most recent version of Next.

**Comment by ematipico** [comment]
Ok, I will keep trying. Any specific VSCode settings? Those are important too, since the CLI doesn't trigger the problem

**Comment by Profesor08** [comment]
There is no specific settings in VSCode, just tried [portable mode](https://code.visualstudio.com/docs/editor/portable), installed [biome extension](https://marketplace.visualstudio.com/items?itemName=biomejs.biome), `npm run build` - biome.exe eats all memory in a few minutes.

**Comment by ematipico** [comment]
Thank you @Profesor08 , I can definitely reproduce the issue! I'll see what I can do

**Comment by ematipico** [comment]
@arendjr I did some debugging. When running the build of the files, the function `update_module_graph` is triggered by `update_service_data`. 

```
DEBUG biome_service::workspace_watcher watcher_event, event=Event { kind: Create(File), paths: ["/Users/ema/www/biome-memory-leak/dist/static/js/344.94ed1f5f.js"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
```

I tried to comment out `update_module_graph`, and the memory leak is gone. I'm not sure if the watcher event is expected or not. Should we check if the incoming file is ignored or not?

**Comment by dmythro** [comment]
> Ok, I will keep trying. Any specific VSCode settings? Those are important too, since the CLI doesn't trigger the problem 

In my case: yes. I have auto-save on type with a short delay & auto-format on save (btw I never checked if in this case it saves file twice or formats before saving and then saves file once). And I use organize imports, which caused some issues before (now, I have sometimes inconsistency with organize imports via command palette and biome CLI, but it happens not that often).

**Comment by dmythro** [comment]
Oh, I was wrong! Biome used 45.7 GB RAM while MacBook was locked! Wow!

Before it also used a lot of CPU so I knew there's something off because it was warm. Now seems like CPU was not the issue anymore, but RAM still is.

And it definitely is via Biome VSCode extension. Will try previous version for now.

<img width="1021" height="575" alt="Image" src="https://github.com/user-attachments/assets/6a7effd3-3729-4ff3-99c6-fb0441c16fe6" />

**Comment by devlsh** [comment]
> Oh, I was wrong! Biome used 45.7 GB RAM while MacBook was locked! Wow!
> 
> Before it also used a lot of CPU so I knew there's something off because it was warm. Now seems like CPU was not the issue anymore, but RAM still is.
> 
> And it definitely is via Biome VSCode extension. Will try previous version for now.
> 
> <img width="1021" height="575" alt="Image" src="https://github.com/user-attachments/assets/6a7effd3-3729-4ff3-99c6-fb0441c16fe6" />

this is my issue too - 64gb ram, linux, vscode extension - biome eventually uses 98% ram during longer sessions before i notice and restart vscode 

can't create a repro right now with my time constraints, but guessing it's reproducible given previous comments - wasn't an issue until i recently updated to latest cli (or extension?)

**Comment by yadunut** [comment]
This appears in the Zed's biome extension (v0.2.0) as well. 
```
> biome rage
CLI:
  Version:                      2.0.0
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  BIOME_THREADS:                unset
  NO_COLOR:                     unset
  TERM:                         xterm-ghostty
  JS_RUNTIME_VERSION:           v22.14.0
  JS_RUNTIME_NAME:              node
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       Loaded successfully
  Path:                         biome.json
  Formatter enabled:            true
  Linter enabled:               true
  Assist enabled:               true
  VCS enabled:                  true

Workspace:
  Open Documents:               0
```
and the config file
```json
{
  "$schema": "https://biomejs.dev/schemas/2.0.0/schema.json",
  "files": {
    "includes": ["**", "!**/assets/**/*"]
  },
  "vcs": {
    "enabled": true,
    "clientKind": "git",
    "useIgnoreFile": true
  },
  "assist": {
    "enabled": true,
    "actions": { "source": { "organizeImports": "on" } }
  },
  "linter": {
    "enabled": true,
    "domains": {
      "react": "all",
      "project": "recommended"
    },
    "rules": {
      "recommended": true,
      "correctness": {
        "noUnusedImports": {
          "level": "warn",
          "fix": "safe"
        }
      },
      "style": {
        "noParameterAssign": "error",
        "useAsConstAssertion": "error",
        "useDefaultParameterLast": "error",
        "useEnumInitializers": "error",
        "useSelfClosingElements": "error",
        "useSingleVarDeclarator": "error",
        "noUnusedTemplateLiteral": "error",
        "useNumberNamespace": "error",
        "noInferrableTypes": "error",
        "noUselessElse": "error"
      }
    }
  },
  "formatter": {
    "enabled": true,
    "indentStyle": "space",
    "indentWidth": 2
  },
  "javascript": {
    "formatter": {
      "semicolons": "always",
      "trailingCommas": "all"
    }
  }
}
```

I've not looked into what is causing this for Zed, but it seems to be similar.

**Comment by ematipico** [comment]
If I understand correctly, the issue doesn't happen with the CLI. Only when using the editor, and when working with your project for a while.

With a reproduction shared here, a ignored file was built, and that caused the memory leak

**Comment by joel-olazagasti** [comment]
If it's helpful, it seems like the LSP is receiving a new publishDiagnostics notification for every file open in the editor whenever a build is triggered (vite hot reloading in my case). I didn't see any diagnostic requests or traces otherwise for ignored files. Seemingly, the memory growth is proportional to the number of open files, so I'm assuming that's related. If I save a file without a dev server running, I only get traces for the saved file and other open files in its module graph.

**Comment by Profesor08** [comment]
@ematipico in cli mode, it do it's job and dies. It happens whe biome in lsp server mode.

**Comment by plutack** [comment]
I noticed this too some hours ago which was how I found this issue. I use helix with biome set as  lsp. I am on version  2.1.1 on  Linux

**Comment by ematipico** [comment]
> If it's helpful, it seems like the LSP is receiving a new publishDiagnostics notification for every file open in the editor whenever a build is triggered (vite hot reloading in my case). 

Sounds about right and that's expected :)

**Comment by joel-olazagasti** [comment]
Does anyone have suggestions for good workarounds (other than manually calling the `restart biome` extension command periodically) for the time being until a fix is in? I tinkered with killing the LSP process parallel to the hot-reloading script, but unfortunately the extension won't restart the LSP server if there are >5 crashes in 3 minutes. I tried restarting the LSP process and proxy manually, but of course the extension doesn't know to attach to it at that point.

**Comment by dmythro** [comment]
> Does anyone have suggestions for good workarounds (other than manually calling the `restart biome` extension command periodically) for the time being until a fix is in?

I downgraded to v2.0.6 for now and didn't have such crazy memory leaks so far (at least for the last 2h of work with `next dev`).

**Comment by jcajuab** [comment]
> If I understand correctly, the issue doesn't happen with the CLI. Only when using the editor, and when working with your project for a while.
> 
> With a reproduction shared here, a ignored file was built, and that caused the memory leak

I'm not sure if this is the intended behavior, but in Biome v2.1.1, I excluded a file using `files.include` and ran `biome check`. The CLI ignored the file as expected. However, when I opened the same file in VSCode, it still lints it. While v2.0.6 does not lint the ignored file.

> I downgraded to v2.0.6 for now and didn't have such crazy memory leaks so far (at least for the last 2h of work with next dev).

I also downgraded to v2.0.6 and didn't experience any memory leak.

**Comment by ematipico** [comment]
No it's not the intended behaviour

**Comment by ematipico** [comment]
@jcajuab 

That seems to be a separate problem, unrelated to this one. I suggest you to check if someone else filed a similar issue, and if not create one.

**Comment by arendjr** [comment]
@ematipico I think @jcajuab's comment might actually be an important insight here. I'm not aware what changed between 2.0.6 and 2.1.0 that could have caused this, but if `files.includes` isn't being respected properly anymore in the new version, that could explain most complaints in this thread, because that means that people's minified files are likely not getting properly ignored anymore either.

**Comment by arendjr** [comment]
> I tried to comment out `update_module_graph`, and the memory leak is gone. I'm not sure if the watcher event is expected or not. Should we check if the incoming file is ignored or not?

Sorry, missed this one first time. But yeah, this does align with @jcajuab 's observation that ignored files are getting processed that shouldn't be. So while it makes sense that `update_module_graph` fixes it, the real issue is one step before that. When we received the watcher event, we should have checked it against the ignored files before even going into `open_file_internal`.

The odd thing is, I think we _did_ that. But then if we see that files are also getting _linted_ that shouldn't be, I think the issue might be a more general one with the LSP: It seems something related to _loading_ of included/ignored files is broken there.

**Comment by arendjr** [comment]
Oh wait, it seems the check inside the watcher _only_ checks against scanner ignores, not `files.includes` in general. I was focused on trying to explain what changed in 2.1, but this would've been an issue since 2.0, I think.

**Comment by RunOrVeith** [comment]
Yes I found this today as well, but I am using 2.0.6 and the watched files are way too high https://github.com/biomejs/biome/issues/6838

**Comment by ematipico** [comment]
> Oh wait, it seems the check inside the watcher _only_ checks against scanner ignores, not `files.includes` in general. I was focused on trying to explain what changed in 2.1, but this would've been an issue since 2.0, I think.

I'll fix that in https://github.com/biomejs/biome/pull/6839

**Comment by kosta** [comment]
> Oh wait, it seems the check inside the watcher only checks against scanner ignores, not files.includes in general. I was focused on trying to explain what changed in 2.1, but this would've been an issue since 2.0, I think.

Is there a specific vscode settings.json or biome.json setting we can use as a workaround?

**Comment by ematipico** [comment]
Not sure, but I suggest downgrading to avoid headaches into finding a proper solution, since it changes by project

**Comment by lmyslinski** [comment]
I just reproduced this on linux. I've had 2 crashes today since upgrading to 2.1.1, I've also installed the CLI for VSCode integration to work

**Comment by AndreiTS** [comment]
💀 
<img width="502" height="302" alt="Image" src="https://github.com/user-attachments/assets/83e31bc1-8660-44ce-8ad4-6bb2f5de2634" />

**Comment by JoanLaRosa** [comment]
Switching to 2.0.5 fixed it for me, easiest way to test the memory leak is running a build

**Comment by trevorpfiz** [comment]
> > Oh wait, it seems the check inside the watcher only checks against scanner ignores, not files.includes in general. I was focused on trying to explain what changed in 2.1, but this would've been an issue since 2.0, I think.
> 
> Is there a specific vscode settings.json or biome.json setting we can use as a workaround?

This seems to be a workaround for me:
```json
{
  "$schema": "https://biomejs.dev/schemas/2.1.1/schema.json",
  "extends": ["ultracite"],
  "files": {
    "includes": [
      "**",
      "!**/node_modules/**",
      "!**/dist/**",
      "!**/.sst/**",
      "!**/.turbo/**",
      "!**/.venv/**",
      "!**/packages/design-system/components/ui/**",
      "!**/packages/design-system/lib/**",
      "!**/packages/design-system/hooks/**",
      "!**/apps/email/.react-email/**"
    ],
    "experimentalScannerIgnores": [
      "node_modules",
      "dist",
      ".sst",
      ".next",
      ".turbo",
      ".venv"
    ]
  }
}

```

**Comment by walkerdb** [comment]
also reporting in on macOS, my main biome lsp process is currently at 40gb ram used, I've seen it up to 50gb. This is since updating to 2.1.1, seems new after the bump up from 2.0.6?

<img width="442" height="197" alt="Image" src="https://github.com/user-attachments/assets/f5bb3c22-f8b2-456a-a497-2ed677816f56" />

**Comment by walkerdb** [comment]
happy to help debug if there's anything I can do from my end! We run a very large private monorepo so I can't easily share code, but I'm happy to run debug builds or commands.

**Comment by flamrdevs** [comment]
in my case

<img width="907" height="75" alt="Image" src="https://github.com/user-attachments/assets/38e077cd-f69e-4314-98d1-923443563169" />

```
CLI:
  Version:                      2.1.1
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           windows

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  BIOME_THREADS:                unset
  NO_COLOR:                     unset
  TERM:                         unset
  JS_RUNTIME_VERSION:           v24.2.0
  JS_RUNTIME_NAME:              node
  NODE_PACKAGE_MANAGER:         pnpm/10.10.0

Biome Configuration:
  Status:                       Loaded successfully
  Path:                         biome.json
  Formatter enabled:            true
  Linter enabled:               true
  Assist enabled:               true
  VCS enabled:                  true

Workspace:
  Open Documents:               0
```

**Comment by ematipico** [comment]
Please try the following preview release and confirm if it fixes the problem.

```shell
 npm i https://pkg.pr.new/biomejs/biome/@biomejs/biome@a6874f9
```

Please don't use this release as a workaround fix, if possible. We discourage the use of preview releases in production because they use a registry that is different from `npmjs`.

**Comment by Yungshween** [comment]
Just reproduced on MacOS, but may have found a temporary fix.

  **Environment:**
  - OS: macOS 26.0 beta
  - Biome: 2.1.0 & 2.1.1
  - VS Code Extension: 2025.7.41733

**Discovery:**
Running build and/or local dev server launch commands appears to trigger background daemon processes for any/all installed biome versions. In my case spawned numerous 2.0.6 instances.

**Workaround:**
Explicitly uninstalling older/unused Biome versions globally appears to have resolved this for me.

**Steps to Fix**
1. Check for running daemons - note specific versions/installations
```bash
biome rage --daemon-logs --formatter --linter
```

2. Check output for unintended versions running in the background. Uninstall any that are not the intended version. I did this globally just to be safe. 
```bash
npm uninstall -g @biomejs/biome@[version]
```

In my case the performance/memory usage improved almost immediately. Unsure what the long term solution would be but appears the cause could be:
  1. Multiple daemon instances not properly cleaning up
  2. Daemons persisting across different project contexts

Hope this helps others experiencing the issue, and might provide some insight for a permanent fix!

**Comment by walkerdb** [comment]
@ematipico so far in my local testing on `https://pkg.pr.new/biomejs/biome/@biomejs/biome@a6874f9` I can no longer replicate the RAM issue on our codebase.

**Comment by nicholas-johnson-techxcel** [comment]
v2.1.1 you are going to wreck my Macbook SSD with the swapfile. It happened multiple times. This seems to not be a Windows-specific bug.

<img width="531" height="139" alt="Image" src="https://github.com/user-attachments/assets/d4d8050f-9e28-446f-8196-a34dd7cc8b1c" />

**Comment by Its-Satyajit** [comment]
<img width="1751" height="243" alt="Image" src="https://github.com/user-attachments/assets/5af789ca-9b22-49db-8ea5-8aa07f9b2a10" />

With out starting dev server


## File: biome.jsonc
```jsonc
{
	"$schema": "./node_modules/@biomejs/biome/configuration_schema.json",
	"assist": {
		"actions": {
			"recommended": true,
			"source": {
				"organizeImports": "on",
				"recommended": true,
				"useSortedAttributes": "on",
				"useSortedProperties": "on"
			}
		},
		"enabled": true
	},
	"files": {
		"ignoreUnknown": false,
		"includes": [
			"**",
			"!**/node_modules/**",
			"!**/.next/**",
			"!**/out/**",
			"!**/.vercel/**"
		]
	},
	"formatter": { "enabled": true, "useEditorconfig": true },
	"linter": {
		"enabled": true,
		"rules": {
			"nursery": {
				"useSortedClasses": {
					"fix": "safe",
					"level": "warn",
					"options": { "functions": ["clsx", "cva", "cn"] }
				}
			},
			"recommended": true
		}
	},
	"root": true,
	"vcs": { "clientKind": "git", "enabled": true, "useIgnoreFile": true }
}

```

## File: package.json
```json
{
	"name": "hidden",
	"version": "0.1.10",
	"private": true,
	"type": "module",
	"scripts": {
		"build": "next build",
		"check": "biome check .",
		"check:unsafe": "biome check --write --unsafe .",
		"check:write": "biome check --write .",
		"db:generate": "drizzle-kit generate",
		"db:migrate": "drizzle-kit migrate",
		"db:push": "drizzle-kit push",
		"db:studio": "drizzle-kit studio",
		"dev": "next dev --turbo",
		"preview": "next build && next start",
		"start": "next start",
		"typecheck": "tsc --noEmit"
	},
	"dependencies": {
		"@radix-ui/react-avatar": "^1.1.10",
		"@radix-ui/react-dialog": "^1.1.14",
		"@radix-ui/react-label": "^2.1.7",
		"@radix-ui/react-navigation-menu": "^1.2.13",
		"@radix-ui/react-select": "^2.2.5",
		"@radix-ui/react-slot": "^1.2.3",
		"@t3-oss/env-nextjs": "^0.13.8",
		"@tanstack/react-form": "^1.14.1",
		"class-variance-authority": "^0.7.1",
		"clsx": "^2.1.1",
		"drizzle-orm": "^0.44.3",
		"lucide-react": "^0.525.0",
		"motion": "^12.23.5",
		"mysql2": "^3.14.2",
		"neverthrow": "^8.2.0",
		"next": "^15.4.1",
		"react": "^19.1.0",
		"react-dom": "^19.1.0",
		"tailwind-merge": "^3.3.1",
		"tailwindcss-animated": "^2.0.0",
		"vaul": "^1.1.2",
		"zod": "^4.0.5"
	},
	"devDependencies": {
		"@biomejs/biome": "2.1.1",
		"@tailwindcss/postcss": "4.1.11",
		"@types/node": "24.0.13",
		"@types/react": "19.1.8",
		"@types/react-dom": "19.1.6",
		"babel-plugin-react-compiler": "19.1.0-rc.2",
		"drizzle-kit": "0.31.4",
		"postcss": "8.5.6",
		"tailwindcss": "4.1.11",
		"tw-animate-css": "1.3.5",
		"typescript": "5.8.3"
	},
	"ct3aMetadata": {
		"initVersion": "7.39.3"
	},
	"packageManager": "pnpm@10.13.1"
}
```

```
fastfetch
          ,...,                                 its-satyajit@localhost
     .,:lloooooc;.                              ----------------------
   ,ool'     oo,;oo:                            OS: openSUSE Tumbleweed x86_64
 .lo'        oo.   oo:                          Host: G3 3579
.oo.         oo.    oo:                         Kernel: Linux 6.15.5-1-default
:ol          oo.    'oo                         Uptime: 35 mins
:oo         .oo.    .oo.                        Packages: 3689 (rpm), 13 (flatpak)
.oooooooooooooo.    .oo.                        Shell: zsh 5.9
 ;oo.               .oo.                        Display (LED): 1366x768 @ 60 Hz (as 1932x1086) in 19" [External]
  'oo,              .oo.                        Display (LGD053F): 1920x1080 @ 60 Hz in 16" [Built-in] *
    "ooc,',,,,,,,,,,:ooc,,,,,,,,,,,             DE: KDE Plasma 6.4.2
       ':cooooooooooooooooooooooooool;.         WM: KWin (Wayland)
                    .oo.             .oo;       WM Theme: Breeze
                    .oo.               .oo.     Theme: Breeze (OpenSUSEDarkMod) [Qt], Breeze-Dark [GTK2], Breeze [GTK3]
                    .oo.    'oooooooooo:ooo.    Icons: Papirus-Dark [Qt], Papirus-Dark [GTK2/3/4]
                    .oo.    'oo.         col    Font: Noto Sans (10pt) [Qt], Noto Sans (10pt) [GTK2/3/4]
                    .oo'    'oo          col    Cursor: breeze (24px)
                     coo    'oo          oo'    Terminal: warp v0.2025.07.09.08.11.stable_01
                      coc   'oo        .lo,     Terminal Font: Maple Mono (14.0pt)
                       `oo, 'oo      .:oo       CPU: Intel(R) Core(TM) i7-8750H (12) @ 4.10 GHz
                         'ooooc,, ,:lol         GPU 1: NVIDIA GeForce GTX 1050 Ti Mobile [Discrete]
                            `''"clc"'           GPU 2: Intel UHD Graphics 630 @ 1.10 GHz [Integrated]
                                                Memory: 8.02 GiB / 31.19 GiB (26%)
                                                Swap: 1.90 GiB / 10.00 GiB (19%)
                                                Disk (/): 35.40 GiB / 49.00 GiB (72%) - btrfs
                                                Disk (/home): 39.41 GiB / 67.92 GiB (58%) - xfs
                                                Disk (/media/Dump): 95.62 GiB / 310.58 GiB (31%) - btrfs
                                                Disk (/media/Everything Else): 187.75 GiB / 310.46 GiB (60%) - fuseblk
                                                Local IP (p6p1): 192.168.1.162/24
                                                Locale: en_US.UTF-8

                                                                        
                                                                        
```

**Comment by RunOrVeith** [comment]
With this prerelease, I also got OOM killed immediately after opening cursor with the biome extension enabled on Ubuntu. This did not happen before, I now have this issue in addition to https://github.com/biomejs/biome/issues/6838

**Comment by quick007** [comment]
Any ETA for this to get pushed to NPM? Using an alternate package manager isn't ideal for me.

**Comment by thedevtoni** [comment]
Running into the same issue 

<img width="973" height="192" alt="Image" src="https://github.com/user-attachments/assets/facb3236-166b-4f46-baeb-3b93213869e9" />

Did work for some minutes after following the @Yungshween recommendation. But now is even going hire in memory consumption

**Comment by dyc3** [comment]
@thedevtoni have you tried the preview release yet? mentioned here: https://github.com/biomejs/biome/issues/6784#issuecomment-3067117855

As mentioned, we don't encourage using preview builds in prod, but it would be useful to have the extra validation.

**Comment by qxprakash** [comment]
> Please try the following preview release and confirm if it fixes the problem.
> 
>  npm i https://pkg.pr.new/biomejs/biome/@biomejs/biome@a6874f9
> Please don't use this release as a workaround fix, if possible. We discourage the use of preview releases in production because they use a registry that is different from `npmjs`.

Hi @ematipico I installed the fix which you suggested 

stilling facing the the same issue , biome is taking around 9GB

<img width="550" height="1380" alt="Image" src="https://github.com/user-attachments/assets/813b90d3-30d5-480f-b330-2c6a6afcaa7e" />

**Comment by arendjr** [comment]
@qxprakash Does the memory consumption go up immediately after enabling the Biome extension? Or does it happen after a while, for instance, when you create a build?

**Comment by Shahfarzane** [comment]
I have the same issue on MacBook Pro M4 Pro with 24g ram and  8gig of ram is used by biome !

**Comment by qxprakash** [comment]
> [@qxprakash](https://github.com/qxprakash) Does the memory consumption go up immediately after enabling the Biome extension? Or does it happen after a while, for instance, when you create a build?

A bit of context: I had installed Biome globally using Homebrew, then uninstalled it and installed the preview release globally using: `npm i -g https://pkg.pr.new/biomejs/biome/@biomejs/biome@a6874f9` , It worked fine for a day, but the next day, it started showing high RAM usage again , also consumption didn't go up immediately.

**Comment by mikkurogue** [comment]
> [@qxprakash](https://github.com/qxprakash) Does the memory consumption go up immediately after enabling the Biome extension? Or does it happen after a while, for instance, when you create a build?

for us, anyone using VSCode or Cursor has this happen and it increases when we run our build command. I do not have this issue, for some reason, in neovim. I only have it that it will consume "alot" of memory but eventually stay stable.

edit: on macos with both M1 and M3 pro cpus.

**Comment by nilskaspersson** [comment]
> [@qxprakash](https://github.com/qxprakash) Does the memory consumption go up immediately after enabling the Biome extension? Or does it happen after a while, for instance, when you create a build?

I observe the memory leak happen immediately after I `next build`, _if I have the extension on/LSP server running in my editor (Cursor)_. 

The biome instance ticks up ~1 GB of memory every few seconds, until eventually there's nothing left for it to reserve. This never stops until it's manually killed (or the IDE is closed)—even after the build has finished. It's very strange, because the build shouldn't even be invoking biome.

At first I though I have it watch the built files, but my biome config specifies paths like this, so it shouldn't (?):

```
"includes": [
	"src/**",
	"next.config.ts",
	"drizzle.config.ts",
	"vitest.config.ts"
]
```

M1 Macbook, if relevant. Only tested on `v2.1.1`.

And to be clear: I have _only_ observed the memory leak in this exact context. As long as I don't `next build`, I've had the IDE running on this project for days of heavy usage, without issues.

**Comment by rytido** [comment]
I have a MacBook Air M1 and after a vite build also see massive cpu/memory usage that persists until biome is restarted. It seems to affect 2.1.1 but not 2.0.6.

**Comment by dmythro** [comment]
Hope it helps: I've been using 2.x (I have 2.1.1 globally and 2.0.6 in projects) for a couple of days with [a config like this](https://github.com/dmythro/dmythro.com/blob/main/biome.jsonc), and seen no memory leaks so far (I ignore css files because of the Tailwind VSCode extension so far):

```jsonc
  "files": {
    "ignoreUnknown": true,
    "includes": ["**", "!**/*.css", "!.next", "!data/test/**", "!node_modules"],
    "experimentalScannerIgnores": [".next", "dist", "node_modules"]
  },
```

All leaks stopped with `experimentalScannerIgnores` basically. Without it, memory leaks got back eventually (not right away).

**Comment by thedevtoni** [comment]
> [@thedevtoni](https://github.com/thedevtoni) have you tried the preview release yet? mentioned here: [#6784 (comment)](https://github.com/biomejs/biome/issues/6784#issuecomment-3067117855)
> 
> As mentioned, we don't encourage using preview builds in prod, but it would be useful to have the extra validation.

Have to disable the extension for Cursor because it was unusable. The whole system was crashing even after applying the patch. I have a very large monorepo. But disabling the extension worked for me.

**Comment by convcha** [comment]
`experimentalScannerIgnores` works in my environment (2.1.1).
Thanks to @trevorpfiz and @dmythro !

```jsonc
"files": {
  "ignoreUnknown": true,
  "includes": [
    "**",
    "!**/worker-configuration.d.ts",
    "!packages/web/app/components/Icon/Icon.tsx",
    "!**/node_modules/**",
    "!**/public/**",
    "!**/.wrangler/**",
    "!**/dist/**",
    "!**/patches/**",
    "!**/.react-router/**",
    "!**/.turbo/**",
    "!**/out/**",
    "!**/build/**"
  ],
  "experimentalScannerIgnores": [
    "public",
    ".wrangler",
    "node_modules",
    "dist",
    "patches",
    ".react-router",
    ".turbo",
    "out",
    "build"
  ]
},
```

**Comment by ematipico** [comment]
Please everyone, refrain from adding comments with just screenshots. Use the upvotes feature.

Instead, please try this new preview release and tell us of that helps.

New preview release available for `@biomejs/biome`. Install it using the following command:

 ```bash
 npm i https://pkg.pr.new/biomejs/biome/@biomejs/biome@6d68074
```

**Comment by prostarz** [comment]
> Please everyone, refrain from adding comments with just screenshots. Use the upvotes feature.
> 
> Instead, please try this new preview release and tell us of that helps.
> 
> New preview release available for `@biomejs/biome`. Install it using the following command:
> 
> npm i https://pkg.pr.new/biomejs/biome/@biomejs/biome@6d68074

after using this release for about 20 minutes or so, the memory is now at a steady 30mb, as before (v2.1.1) within about 2 minutes of opening my editor the memory of biome.exe would go up to 100% memory usage

**Comment by ematipico** [comment]
For people that are still hitting the leak: if you can help, here are few resources that could help you investigating what triggers the malfunction:
- https://biomejs.dev/guides/investigate-slowness/
- https://biomejs.dev/guides/editors/create-a-extension/#daemon-logs

Then see if you can find a consistent way to trigger it, and share it with us. We appreciate the help .

**Comment by jacsamg** [comment]
This is happening to me in an new Angular v19 project, after running "ng build". 

Windows 11.
Biome version 2.1.1.
It is installed with npm in the project and globally.

biome.json:
```json
{
  "$schema": "./node_modules/@biomejs/biome/configuration_schema.json",
  "vcs": {
    "enabled": false,
    "clientKind": "git",
    "useIgnoreFile": false
  },
  "files": {
    "ignoreUnknown": true,
    "includes": [
      "src/**",
      "!src/modules/shared/**"
    ]
  },
  "formatter": {
    "enabled": true,
    "indentStyle": "space",
    "useEditorconfig": true
  },
  "linter": {
    "enabled": true,
    "rules": {
      "recommended": true,
      "style": {
        "noNonNullAssertion": "off"
      },
      "complexity": {
        "useLiteralKeys": "off"
      }
    }
  },
  "javascript": {
    "formatter": {
      "quoteStyle": "single"
    }
  },
  "assist": {
    "enabled": true,
    "actions": {
      "source": {
        "organizeImports": "on"
      }
    }
  }
}
```

**Comment by jacsamg** [comment]
After trying several configurations, the following one worked. I no longer have the problem after the "ng build." I assume the problem was with the ".angular" or "www" folder.

biome.json
```json
"files": {
    "ignoreUnknown": true,
    "includes": [
      "src/**",
      "!src/modules/shared"
    ],
    "experimentalScannerIgnores": [
      ".angular",
      ".git",
      "node_modules",
      "www"
    ]
  }
```

**Comment by ematipico** [comment]
It seems that the watcher still tries to read folders that are ignored. @jacsamg does that happen with any angular project?

**Comment by Mkassabov** [comment]
> New preview release available for `@biomejs/biome`. Install it using the following command:
> 
> npm i https://pkg.pr.new/biomejs/biome/@biomejs/biome@6d68074

Seems to fix it for us. any idea when the next release with this will be?

**Comment by dyc3** [comment]
@Mkassabov We generally don't provide ETAs, but I think its safe to say that at least a patch release will be soon.

**Comment by heliocj** [comment]
Well, that is the same here after upgraded to 2.1.1. Using 100% of memory. I have to close the vscode, kill the biome proccess and open vscode again.

**Comment by RunOrVeith** [comment]
This last preview release triggers it for me in the first place - within a few seconds of opening the IDE I get OOM killed. I did not have this problem before.

**Comment by dbushell** [comment]
Also a memory leak on 2.1.1 on macOS if that helps

<img width="720" height="128" alt="Image" src="https://github.com/user-attachments/assets/a3b24798-2bb6-4fe0-9147-9ab4419ef8ee" />

possibly related:

https://github.com/user-attachments/assets/8c6e0f59-7366-4b16-8934-30668c84f887

**Comment by animeshxd** [comment]
On linux 6.15.6
biome Version: 2.1.1
```
Jul 17 18:07:05 arch kernel: oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/session-1.scope,task=biome,pid=61424,uid=1000
Jul 17 18:07:05 arch kernel: Out of memory: Killed process 61424 (biome) total-vm:33800476kB, anon-rss:25877624kB, file-rss:460kB, shmem-rss:0kB, UID:1000 pgtables:51028kB oom_score_adj:0
Jul 17 18:07:05 arch systemd[1]: session-1.scope: A process of this unit has been killed by the OOM killer.
```

**Comment by yyong008** [comment]
<img width="717" height="105" alt="Image" src="https://github.com/user-attachments/assets/d73f94c9-7935-4a28-ab1f-9891d596ac5c" />

macOS, v2, Takes up a huge amount of memory

**Comment by ematipico** [comment]
v2.1.2 is out, please test it. Make sure to close the editor and kill any pending `biome` - just in case. We will keep the issue open for a little while.

> [!IMPORTANT]
> If you still face the issue, please share information of **how to replicate the issues** like detailed steps, dependencies installed and any shell scripts that you run while your editor is open. 
> We might hide your comment if such information isn't provided, because we are receiving too much noise, and it's difficult to filter important information to us.

**Comment by Profesor08** [comment]
In my case issue is fixed

**Comment by li-yechao** [comment]
This issue still exist on my macOS, reproduce steps:

1. open a project and open an ts file
2. reload vscode window
3. memory usage will grow up to very high level

NOTICE: **If reload window while focus editor on biome.json file, the memory usage is normal**

<img width="2366" height="476" alt="Image" src="https://github.com/user-attachments/assets/4d1c6625-1f9f-436b-807a-697152da8cdf" />

This is some logs: **Looks like it is checking files in node_modules**

<img width="3024" height="1570" alt="Image" src="https://github.com/user-attachments/assets/8e02edc3-9510-4f54-87aa-a8caf40e3cb3" />


Here is my biome.json

```json
{
  "$schema": "https://biomejs.dev/schemas/2.1.2/schema.json",
  "vcs": {
    "enabled": false,
    "clientKind": "git",
    "useIgnoreFile": true
  },
  "files": {
    "ignoreUnknown": true,
    "includes": [
      "**",
      "!docs/**",
      "!node_modules/**",
      "!**/node_modules/**",
      "!**/lib/**",
      "!**/dist/**",
      "!**/package.json",
      "!**/.oauth/**",
      "!**/.blocklet/**",
      "!observability/api/api/server/utils/modelPricesAndContextWindow.json"
    ],
    "experimentalScannerIgnores": ["node_modules"]
  },
  "formatter": {
    "enabled": true,
    "indentStyle": "space",
    "lineWidth": 100
  },
  "linter": {
    "enabled": true,
    "rules": {
      "recommended": true,
      "correctness": {
        "useImportExtensions": "error",
        "noUnusedVariables": "error",
        "noUnusedImports": "error",
        "noUnusedFunctionParameters": "error",
        "noUnusedPrivateClassMembers": "error"
      },
      "suspicious": {
        "noConfusingVoidType": "off",
        "noExplicitAny": "off"
      },
      "complexity": {
        "noForEach": "off",
        "useLiteralKeys": "off"
      }
    }
  },
  "javascript": {
    "formatter": {
      "quoteStyle": "double"
    }
  },
  "assist": {
    "enabled": true,
    "actions": {
      "source": {
        "organizeImports": "on"
      }
    }
  }
}

```

**Comment by ematipico** [comment]
@li-yechao refer to this comment of mine https://github.com/biomejs/biome/issues/6784#issuecomment-3080377942 to provide more detailed information to us. Preferably, we would like a minimal reproduction

**Comment by li-yechao** [comment]
> [@li-yechao](https://github.com/li-yechao) refer to this comment of mine [#6784 (comment)](https://github.com/biomejs/biome/issues/6784#issuecomment-3080377942) to provide more detailed information to us. Preferably, we would like a minimal reproduction

Reproduction steps:

1. clone <https://github.com/AIGNE-io/aigne-framework>
2. pnpm install && pnpm build
3. open project in vscode
4. open file `package.json` in the vscode
5. `CMD + SHIFT + p` -> reload window
6. the biome process will use more and more memory

More information:
7. delte folder `tests/browser/dist`
8. CMD + SHIFT + p` -> reload window
9. the memory usage just stoped at around 300M

Notice: 
- Here is other dist folder in the workspace, such as `packages/cli/dist`, but seems like only `tests/browser/dist` folder cause memory leak
- And I have tried to set `files#include` to `["**", "!**/dist/**"]`, it also not work

https://github.com/user-attachments/assets/34cc9d37-4027-41ae-933a-6c01f8f13fb4

**Comment by jacsamg** [comment]
> It seems that the watcher still tries to read folders that are ignored. [@jacsamg](https://github.com/jacsamg) does that happen with any angular project?

@ematipico Sorry, I didn't have time to check it that day. Today I decided to do it on a clean project and saw that there was an update. There was no leak with the default Biome configuration.

I updated to '2.1.2' in the project where I had the problem (and global) and also reverted to the basic rules; the problem disappeared. Thanks for your work!

biome.json
```json
"files": {
    "ignoreUnknown": true,
    "includes": [
      "src/**",
      "!src/modules/shared"
    ]
  }
```

**Comment by mbret** [comment]
Did I win the prize yet ?

<img width="768" height="354" alt="Image" src="https://github.com/user-attachments/assets/3db654fc-8ecf-46db-8b3b-f685c9ac9d58" />

**Comment by arendjr** [comment]
Thanks a ton, @li-yechao ! I was actually able to reproduce the issue with your repository.

Interestingly, I can also resolve it locally by pointing the LSP at a local build from `main`. Normally, that would suggest we've already fixed the issue, but I can actually not fully explain that. The only relevant fix in `main` would be e6b238063f92bc95d951e3a78dac42408d0814c0, but if that one had solved it, I would expect `biome lint` to have had the issue too and there should be a diagnostic about a recursive hook now, which is not the case. So I need to dive a little deeper, but I'm really happy with this one!

**Comment by jpike88** [comment]
I have latest `@biomejs/biome@2.1.2` installed, and am using the biome extension via the Zed Editor.

Each time I save on a file (doesn't matter which), it seems that the biome process memory just increases each time and never decreases.

After using for a while... it just bloats bigger and bigger.

<img width="632" height="77" alt="Image" src="https://github.com/user-attachments/assets/4d054c46-c706-4133-8751-30f5c07b8b49" />


My biome.json:

```
{
	"$schema": "./node_modules/@biomejs/biome/configuration_schema.json",
	"formatter": {
		"enabled": false
	},
	"assist": {
		"actions": {
			"source": {
				"organizeImports": {
					"level": "on",
					"options": {
						"groups": [
							":NODE:",
							":PACKAGE:",
							":BLANK_LINE:",
							"@/shared/**",
							":BLANK_LINE:",
							":ALIAS:",
							":PATH"
						]
					}
				}
			}
		}
	},
	"javascript": {
		"formatter": {
			"quoteStyle": "single",
			"trailingCommas": "es5"
		},
		"parser": {
			"unsafeParameterDecoratorsEnabled": true
		}
	},
	"linter": {
		"enabled": true,
		"rules": {
			"a11y": {
				"noNoninteractiveTabindex": "error",
				"noRedundantRoles": "error"
			},
			"complexity": {
				"noBannedTypes": "off",
				"noExtraBooleanCast": "off",
				"useSimplifiedLogicExpression": "off",
				"useOptionalChain": "error",
				"noUselessConstructor": "off",
				"noUselessTypeConstraint": "error",
				"noUselessRename": "error",
				"useLiteralKeys": "error",
				"noForEach": "error",
				"noStaticOnlyClass": "off",
				"useArrowFunction": "off",
				"noThisInStatic": "off",
				"useSimpleNumberKeys": "off",
				"useRegexLiterals": "off"
			},
			"performance": {
				"noDelete": "off"
			},
			"suspicious": {
				"noTemplateCurlyInString": "off",
				"noGlobalIsNan": "off",
				"noDoubleEquals": "error",
				"noRedeclare": "off",
				"noDebugger": "error",
				"noShadowRestrictedNames": "off",
				"noExplicitAny": "off",
				"noAsyncPromiseExecutor": "off",
				"noEmptyInterface": "error",
				"noAssignInExpressions": "error",
				"noConsole": {
					"level": "error",
					"options": {
						"allow": ["info", "error", "warn", "time", "timeEnd"]
					}
				},
				"noPrototypeBuiltins": "error",
				"noVar": "error"
			},
			"style": {
				"useConsistentArrayType": {
					"level": "error",
					"options": { "syntax": "shorthand" }
				},
				"useForOf": "error",
				"useImportType": "off",
				"noNamespace": "off",
				"noParameterAssign": "off",
				"useSingleVarDeclarator": "error",
				"useTemplate": "off",
				"noUnusedTemplateLiteral": "error",
				"useConst": "error",
				"useEnumInitializers": "off",
				"useDefaultParameterLast": "off",
				"noInferrableTypes": "off",
				"useLiteralEnumMembers": "error",
				"noUselessElse": "off",
				"noDefaultExport": "error",
				"useAsConstAssertion": "error",
				"useSelfClosingElements": "error",
				"useNumberNamespace": "error",
				"useNamingConvention": {
					"level": "error",
					"options": {
						"strictCase": false
					}
				},
				"noDescendingSpecificity": "off"
			},
			"correctness": {
				"noConstantCondition": "error",
				"noInvalidConstructorSuper": "error",
				"noUnusedVariables": "error",
				"noUnreachable": "error",
				"noUnsafeFinally": "error",
				"noSwitchDeclarations": "off",
				"noSelfAssign": "off",
				"useValidTypeof": "error",
				"noUnusedImports": "error"
			}
		}
	},
	"files": {
		"includes": [
			"**",
			"!**/*.json",
			"!**/*.d.ts",
			"!**/client/src/components/api.ts",
			"!**/seed/src/components/api.ts",
			"!**/tests/src/integration/api.ts",
			"!**/client/src/components/model/TranslationKeys.ts",
			"!**/server/src/components/translations/TranslationKeys.ts",
			"!**/shared/version.ts",
			"!**/Exif.ts",
			"!**/Measurement.ts",
			"!**/ConfigFile.ts",
			"!**/Converter.ts",
			"!**/importBookingUtil.ts",
			"!**/*.js",
			"!**/node_modules"
		]
	}
}

```

**Comment by jpike88** [comment]
To reproduce my above issue, follow below instructions:

[Archive.zip](https://github.com/user-attachments/files/21326653/Archive.zip)

I can reproduce it in this test folder.

1. Unzip folder.
2. run `npm ci`
3. open the folder in zed, then open gulpfile.ts
4. ensure you have format on save enabled, so saving will cause biome to run.
5. Add a new line to line 8 for example. Then save, and biome should then organize imports.
6. Add a new line again, repeat. Keep doing it, and watch the memory usage of biome process start to climb each time a save is done. It seems to be around adding ~5MB of memory each time format is run..

**Comment by mikkurogue** [comment]
@jpike88 Try upgrading to latest 2.1.2 as that is latest and seems to fix most issues (for me at least).

**Comment by jpike88** [comment]
Sorry for the confusion, I'm using 2.1.2, the latest already in my tests.

**Comment by mikkurogue** [comment]
After testing what you provided in Zed myself on Linux I see the memory spikes a bit after organizing imports but eventually stabilizes and goes back down. In neovim i see it spike harder, but mostly due to it saying that the file does not contain valid UTF-8 formatting so I assume this is an issue on my end.

Have you updated the Zed extension? I'm unsure how Zed rolls out extensions and who is responsible for it so its a shot in the dark

**Comment by ematipico** [comment]
@jpike88 

Many users here realised that they didn't ignore folders such as `dist/` or `build/`: folders that are usefully created by build commands, and that are ignored. See if that's your case too.

**Comment by jpike88** [comment]
In https://github.com/biomejs/biome/issues/6784#issuecomment-3092149172 I've attached a folder that I can repro the issue in, there are no hidden files/folders and no build.js artifacts etc... it's a clean folder otherwise. I normally run non-bundled stuff using node 24's experimental type stripping flag anyway.

I have biome 2.1.2 installed in that folder's node_modules, and `~/Library/Application Support/Zed/extensions/work/biome` shows 2.1.2 installed as well as far as the Zed extension is concerned.

**Comment by jpike88** [comment]
Maybe some kind of way to calling the process externally to dump a stack trace might be useful? I'm not familiar with rust but is there a way to have a call tree or reference tree to detect or analyze where some kind of hanging reference or alloc is occurring?

**Comment by arendjr** [comment]
@li-yechao I was able to fix the high memory usage in the `aigne-framework` repository by setting the `experimentalScannerIgnores` like this: `"experimentalScannerIgnores": [".git", "dist", "node_modules"]`. It was the `dist` folder that was the culprit.

**Comment by arendjr** [comment]
@jpike88 I also tried your reproduction, and yes, every time I ran the Organize imports on the `gulpfile.ts` in that repository, I indeed see the memory usage jump by something between 5 and 10MB. However, as @mikkurogue also noticed, **this wasn't an actual memory leak.**

While it may appear to be so, the memory did get reclaimed after I tried it a few more times. All in all, I couldn't get the memory to stay over about 400MB, after which it snapped back to around 200MB. From there it would grow again, until it reached a certain threshold and it would shrink again. I believe what we are looking at here is an artifact of the memory allocator, which avoids doing work over and over for every allocation (that would be horribly slow), and instead it lets the memory grow for a bit, then reclaims it when it grows too much.

**Comment by ematipico** [comment]
> @li-yechao I was able to fix the high memory usage in the `aigne-framework` repository by setting the `experimentalScannerIgnores` like this: `"experimentalScannerIgnores": [".git", "dist", "node_modules"]`. It was the `dist` folder that was the culprit.

Out of curiosity, does that mean that by adding `dist` to `files.includes`, the leak is fixed?

**Comment by arendjr** [comment]
@ematipico Yes, setting `files.includes` to `["**", "!**/dist/**"]` also worked. Unfortunately, `["**", "!**/dist"]` did not.

**Comment by jpike88** [comment]
@arendjr thanks for the explanation, to be fair it was also during a refactor that included turning on import grouping and bulk modifying many files in the IDE, so I may just have gotten spooked. Since then I notice things are fine. You guys can ignore my report

**Comment by arendjr** [comment]
Thanks for all your patience, and your reports everyone! I'm going to close this issue now, as it seems we have no more reproductions left, and most people report their issues as fixed with 2.1.2.

Note we do still have an issue with minified files. This is why it's so important to ignore folders such as `dist` and `build` using either your `files.includes` or `files.experimentalScannerIgnores`.

For more help with fixing and diagnosing such issues, please see: https://biomejs.dev/guides/investigate-slowness/

To stay up-to-date on the issue regarding minified files, please follow: https://github.com/biomejs/biome/issues/6541

I will divert my attention to making the scanner faster in general: https://github.com/biomejs/biome/issues/6965

If despite everything, you think you're still running into a leak and/or high CPU usage, **please create a new issue**. This issue has become difficult to navigate with all the comments, and I don't think we should keep notifying everyone of other issues anymore. For this reason, I will lock the thread as well.
